### ISSUE TITLE
Crash on Launch

### ISSUE THREAD

**Issue by gruntw0rk** [Darkosto/InvasionIssues#10]
No idea why but when it attempts to launch I get a crash with the following details: 
The game crashed whilst initializing game
Error: java.lang.IllegalStateException: Splash thread

Since I saw java I went and updated it immediately, same crash after update.

Crash report here: https://drive.google.com/file/d/0B7VLzmU0p5tVVXpSMUdRNjl2NVk/view?usp=sharing

**Comment by Claycorp** [comment]
Try disabling the loading screen in the splash.properties
You can find it by clicking the modpack instance, then click [...] in the top right, Then click open folder, Open config, find splash.properties and change ``enabled=true`` to ``enabled=false`` then start the pack!

**Comment by gruntw0rk** [comment]
The game crash changed now. After awhile of staring at a black minecraft screen Java encounters an error and closes. The minecraft launcher reappears and says "Game Crash. An unexpected error occurred and the game has crashed. We're sorry for any inconvenience." 

No crash report. Tried a fresh reinstall of the pack, the crash went away but now it's just a perpetual black screen.

**Comment by gruntw0rk** [comment]
On Darkostos suggestion on stream I pointed the curse launcher at my version of java, 1.8 update 121. Now I'm getting another weird response. Immediately after trying to launch the pack I get a java error: Error Java could not create the java virtual machine. Error A fatal exception occurred. Program will exit. Then the launcher comes back with the following information: Invalid maximum heap size -xmx8192. The specified size exceeds the maximum representable size

**Comment by Claycorp** [comment]
Updating java is a last resort to fix something. You likely installed a 32bit and pointed it to that and it can only use up to 3G of ram. 
Undo the java change, Launch the game and open the logs folder and pastebin/gist the FML latest log.

**Comment by gruntw0rk** [comment]
Updating to 64 bit java finally fixed the java issue but now I've got another crash. 

EnderIO: Found the following problem(s) with your installation (That does NOT mean that Ender IO caused the crash or was involved in it in any way. We add this information to help finding common problems, not as an invitation to post any crash you encounter to Ender IO's issue tracker. Always check the stack trace above to see which mod is most likely failing.):
                  * The RF API that is being used (1.5.0 from (guessing) null) differes from that that is reported as being loaded (1.8.9R1.2.0B1 from furnus-1.10.2-1.92.jar).

**Comment by Claycorp** [comment]
Please just post the log....

**Comment by gruntw0rk** [comment]
http://pastebin.com/tbZVC3F7

**Comment by Darkosto** [comment]
Sounds like we got it all fixed up by switching from 32 bit to 64 bit java! :D

**Comment by Darkosto** [comment]
Has this issue been resolved?

**Comment by gruntw0rk** [comment]
No, I've been awaiting a response to my crash log.

**Comment by Darkosto** [comment]
Random idea, but can you take out the mod "Full Screen Window Borderless" and try?

**Comment by Claycorp** [comment]
I didn't ask for a crash log. Also did you ever test changing that config option? You said you did and the crash changed but I never saw that log either.

**Comment by gruntw0rk** [comment]
Sorry Clay I assumed that since the java issue was resolved you wouldn't need the log for that anymore. I posted the crashlog for the new crash.

Darkosto removing full screen window borderless mod did the trick. The pack loads up no problem.
