### ISSUE TITLE
Shield Automatically Blocks Every Attack From Any Direction

### ISSUE THREAD

**Issue by Chromogen** [Darkosto/InvasionIssues#100]
found another bug where the player happens to autoblocks 360 degree everything. crafting, inventory and stuff wont break the block, only using your shield as intendes refreshes

wired bug i cant pinpoint

also sometimes every second weaponswing just does nothing on raiders. might be in connection

**Comment by Darkosto** [comment]
Ohh, yeah. The auto-shield block is something I'm still trying to figure out. Also, missing every second swing shouldn't be from the modpack, I was able to hit consecutive times last night with no problem.

**Comment by Chromogen** [comment]
the 2nd swing thing is not happening all the time. it just occures for a while.

**Comment by Darkosto** [comment]
Interesting! Keep an eye on it from your end and let me know if you keep noticing it and I'll look into some more :)

**Comment by Chromogen** [comment]
for now i found out that hitting through tall grass wont start the weaponswing indicator.

the 2nd swing thing felt like weaponcooldown + 1second. and did happen without grass too.

**Comment by Lurmey** [comment]
Just gonna pop in here and say that the shield bug blocking everything from all angles is a vanilla bug that seems to happen when the player rapidly and repeatedly blocks.
