### ISSUE TITLE
livestock airdrop

### ISSUE THREAD

**Issue by Chromogen** [Darkosto/InvasionIssues#101]
sorry to have another one. as already mentioned in stream, i cant get useful airdrops on livestock.

so far:
11 bats
8 polar bears
12 ocelots
1 horse
8 squids
3 wolves

in creative placing crates / open crates that were droped works fine but in survival mode its kind of funny. maybe its the biome? living in BOP marsh. could you please have another test?

or maybe its just RNGesus who is trolling me hard...

**Comment by Darkosto** [comment]
Honestly, placing them in creative pulls from the same list. I'll take a look in survival and see what happens.

**Comment by vadis365** [comment]
Hello,
As @Darkosto says the mod pulls form the same list no matter what game mode you are in - I suspect that you are just on the receiving end of a run of bad RNG.
Cheers,
Me.
