### ISSUE TITLE
zombie genes

### ISSUE THREAD

**Issue by Chromogen** [Darkosto/InvasionIssues#103]
the only way to get resistance from genetics reborn is to skin zombies / shulkers
both are not available

since it was enabled in genetics reborn config i guess it should be available?
same for zombie-pigmen -> fireproof gene

edit:
zombie pigmen are obtainable by throwing pigs into witchwater
this might be a fun quest ? 😄 
however villagers to zombievillagers (zombiegenes) in witchwater does not work 😢 

also frank n zombie is not craftable due to lack of zombies but sine it is just used for killer joe and we have grinders

**Comment by Darkosto** [comment]
Ah yeah, I should probably fix the Frank'N'Zombie, lol

I really only disabled the overpowered genes in the config and left the rest on.

**Comment by Darkosto** [comment]
I just uploaded 1.0.4 to curse that adds a zombie head and zombie soul vial recipe to fix that up for you.

**Comment by andr9528** [comment]
Zombies spawn in pyramids from spawners tho, so that not exactly an issue i'd say

**Comment by Darkosto** [comment]
Still fixed and relies on less RNG than having to find a structure :)

**Comment by andr9528** [comment]
true, just making sure you actually know that there are zombies in the world :)
