### ISSUE TITLE
Unexpected metal press molds swapping interaction

### ISSUE THREAD

**Issue by andr9528** [Darkosto/InvasionIssues#105]
When swapping molds on Metal Press if a new mold is applied while another is there, the old one is dropped to the ground instead of being returned to the player's inventory.

**Comment by andr9528** [comment]
found another mold and metal press issue, if one break the metal press with a mold on, the mold is voided instead of dropped.

**Comment by Darkosto** [comment]
Yep, that's an Immersive Engineering mechanic and is best reported to them.
