### ISSUE TITLE
Crashing because of Minecolony's Warehouse?

### ISSUE THREAD

**Issue by andr9528** [Darkosto/InvasionIssues#106]
sometimes the game randomly crashes from what looks like the game checking the inventory of the minecolony warehouse. There is no real thing to do, to trigger it, and after the first one i just thought it was a freak crash but it just happened again, so here is the report with both crash logs, hope it help to prevent unnecessary future crashes :)

Crashlog from 01/04 using version 1.02
https://pastebin.com/7aJBhZzc
Crashlog from 04/04 using version 1.03
https://pastebin.com/1qp99i8M

**Comment by andr9528** [comment]
Just had another one of the crashes, they seem to become more frequent, still do not know how to replicate tho.
Crash count: 3

**Comment by Darkosto** [comment]
Unable to replicate in newer versions.
