### ISSUE TITLE
Clean Invasion 1.0.3 server spawn protection issue

### ISSUE THREAD

**Issue by Thoddius** [Darkosto/InvasionIssues#107]
I just set up the new 1.0.3 server and I can't break any blocks unless I am in creative. I am the server admin with op permissions and can't break blocks anywhere even when setting spawn protection to 0. Ideas?

**Comment by Darkosto** [comment]
This is a duplicate issue that has been fixed in 1.0.4. Thank you!

**Comment by Thoddius** [comment]
Okay. Thanks. ETA on the server file availability?

**Comment by Darkosto** [comment]
It's currently under review, so within the next 3-5 minutes :)

**Comment by Thoddius** [comment]
Awesome

**Comment by Darkosto** [comment]
https://minecraft.curseforge.com/projects/invasion/files/2402833
