### ISSUE TITLE
Spikes and Mob Masher

### ISSUE THREAD

**Issue by DarkestStryke** [Darkosto/InvasionIssues#109]
Wondering if its intentional that spikes from Extra Utils, and therefore the Mob Masher are uncraftable due to the weapon levelling system, as as for the AIOT. As it requires you to craft swords which have to enter your inventory, and thus become 'non-vanilla' so that the recipe doesn't recognize them?

Currently tested Stone, Iron, Gold, Diamond spikes and none are craftable due to the swords being unrecongized, at least at the stage of the game I'm currently in.

On another note.. loving the pack :)

**Comment by GenDeathrow** [comment]
if im not mistaken placing a sword in the crafting grid will give you a vanilla sword. not sure if it needs to be fully repaired but seems like it would.

**Comment by Darkosto** [comment]
All of the AIOT recipes were changed to work with the new sword ID's and tested. As far as anything else requiring vanilla swords, put the sword back in the crafting table to convert it.

**Comment by DarkestStryke** [comment]
I've tried this, but after taking it back out, where a recipe requires 3 swords, it converts them back into alternate versions as soon as they hit your inventory

Having just checked the AIOT recipe, the sword is listed as a Dungeon Tactics sword in the stone AIOT, but for the stone spikes, its listed as a Minecraft sword.


http://imgur.com/a/f1OPi

**Comment by Darkosto** [comment]
Are you sure? 

https://i.artdude.uk/darkosto/FmKDx2ua.mp4

**Comment by DarkestStryke** [comment]
In the 1.0.3 i am definitely sure that i couldn't with any of them. No crafting method was working for me. I've just started the update to 1.0.4 and will try it again as soon as i can get back on game.

**Comment by Darkosto** [comment]
Those mods or recipes have not been altered since before the modpack released. Just for clarification, this is another video from when the pack initially release (1.0). 

https://i.artdude.uk/darkosto/9m4jMsjH.mp4

**Comment by Darkosto** [comment]
And this is me crafting the same recipe using the 1.0.3 version of the modpack:

https://i.artdude.uk/darkosto/VDjfYGKX.mp4

**Comment by DarkestStryke** [comment]
Tried after the update happened and no go, reinstalled the pack and Iron/gold/diamond now work, stone just keeps on telling me, via JEI, that I'm missing 2 of the compatible stone swords, which as it obviously does work.. comes down to error between chair and keyboard. 

Thank you for the responses Darkosto.
