### ISSUE TITLE
Need Help 

### ISSUE THREAD

**Issue by wolfe02** [Darkosto/InvasionIssues#11]
missing blocks and items no report or anythings

**Comment by GenDeathrow** [comment]
This needs a lot more information. What were you doing? How do you know its missing, if there is no report? Console logs? Is this a server, or SP. Is this on a world loading? Normally you add in version numbers as well for everything. your java version. 

 Its hard to trouble shoot something with so little information, As we can not reproduce it. With that said, iis this the  "Fatality Missing Blocks and Items" when loading/starting a server?

**Comment by SmallSansSerif** [comment]
Yes I get that too when trying to connect to 1.0 server (on ubuntu linux) from Invasion 1.0 client.

**Comment by SmallSansSerif** [comment]
This is the fix for me BTW: https://github.com/Darkosto/InvasionIssues/issues/7

just rename the original file and remove the one it auto created

"ExtraUtils2.cfg needs to be renamed extrautils2.cfg"

**Comment by wolfe02** [comment]
i fix it is was a server side sorry
