### ISSUE TITLE
Can't Replace Blocks

### ISSUE THREAD

**Issue by unseennote** [Darkosto/InvasionIssues#111]
When I try to break a block and try to put a different one down, said block just turns back into whatever block was there previously. I though it was because my friend may have claimed the land where this is happening but it appears to be happening everywhere I try to build.

**Comment by andr9528** [comment]
what version are you on? might be one of the multiplayer issues that was fixed on version 1.0.4 which is only a few hours old, if i understand Darkosto correctly

**Comment by unseennote** [comment]
1.0.3, I'll check if updating to 1.0.4 fixes

**Comment by Desim8r** [comment]
Are you playing SP or MP?

We are finding that in MP hardened blocks are instabreaking on the client but when you try to place something else there they return. Break them and relog and they are still there. Looks like a desync between client and server.

Causing some real problems cos you can't get rid of them without going into creative
