### ISSUE TITLE
Duplicate versions of Storage Drawers in Server 1.0.4

### ISSUE THREAD

**Issue by Thoddius** [Darkosto/InvasionIssues#112]
Both StorageDrawers-1.10.2-3.6.3.jar and StorageDrawers-1.10.2-3.7.0.jar are in the mods folder for the Invasion 1.0.4 Server.zip download.

**Comment by Darkosto** [comment]
Yep, already fixed and pending review: https://minecraft.curseforge.com/projects/invasion/files/2402833

Thank you!
