### ISSUE TITLE
Spikes

### ISSUE THREAD

**Issue by DarkestStryke** [Darkosto/InvasionIssues#113]
With reference to issue #109

I've tried this, but after taking it back out, where a recipe requires 3 swords, it converts them back into alternate versions as soon as they hit your inventory

Having just checked the AIOT recipe, the sword is listed as a Dungeon Tactics sword in the stone AIOT, but for the stone spikes, its listed as a Minecraft sword.

http://imgur.com/a/f1OPi

**Comment by GenDeathrow** [comment]
Since the other was reopend.. closing this duplicate
