### ISSUE TITLE
splice n dice zombie recipes (suggestion)

### ISSUE THREAD

**Issue by Chromogen** [Darkosto/InvasionIssues#114]
you just added zombie head back into the game, which is nice and all for zombie mob in vial recipe but doublecheck the recipes on the splice n dice.

would be a shame to have all the easy recipes instead of the ones you actually added:
zombie electrode
z-logic-controller

**Comment by Darkosto** [comment]
Recipe for the Slice'N'Splice looks fine to me, what's the issue with it?
