### ISSUE TITLE
Cook That Coal quest showing 14/13 - uncompletable

### ISSUE THREAD

**Issue by Yorkforce** [Darkosto/InvasionIssues#116]
Checked in both SSP and SMP both have same issue in 1.0.4

The quest Cook That Coal in chapter Automation requires 13 coke bricks to be crafted, but crafting more than 13 won't complete it and the extra brick will result in it going to 14/13 but still shows as uncompleted.

https://imgur.com/a/Dbmrr

**Comment by LuciousLisa** [comment]
Could you explain how you're able to craft 13 coke bricks? The recipe for them results in 2 bricks being made at a time, so this puzzles me greatly...
