### ISSUE TITLE
Not able to assemble cutting machine

### ISSUE THREAD

**Issue by andr9528** [Darkosto/InvasionIssues#118]
Placed down all the components in the corresponding ghost blocks, and then right clicked the cutting machine block to assemble, but it just shows a red X over the output hatch

![2017-04-05_17 23 52](https://cloud.githubusercontent.com/assets/21788044/24713304/8f3fa914-1a25-11e7-9410-9904636b7398.png)
 
im still on version 1.0.3, as the 1.0.4 didn't fix many issues, and none that i had trouble with.

**Comment by Darkosto** [comment]
I've put the cutting machine together in multiple versions and they all worked. Something you're doing is incorrect. I suggest checking the holo-projector again to make sure you placeed the parts down 100% correctly.

**Comment by andr9528** [comment]
before your comment, i had already tried to place the hologram beside it and seen that they indeed was correctly placed.
Now i just broke and replaced it all, but it still does not form, any more suggestions?

**Comment by Darkosto** [comment]
What motor is that your using?

**Comment by andr9528** [comment]
on the picture it is an advanced motor, but since the picture i have gotten an elite motor from a quest and placed it there, still does not work tho

**Comment by Ommina** [comment]
Looking at the photo, it looks like you have the controller block facing inward (toward the saw assembly).  I'd try flipping it around 180 degrees so the Cutting Machine green dot is facing outward.

**Comment by andr9528** [comment]
You where correct Ommina, it was facing the wrong direction which is not exactly easy to figure out
