### ISSUE TITLE
Crazy strong herobrine

### ISSUE THREAD

**Issue by andr9528** [Darkosto/InvasionIssues#120]
i was just up against a 160+ hp full adamantine armor herobrine, and as my primary weapon is a fully enchanted boomerang, it took me 26 deaths to kill him (i'm playing with keepinventory true) with an uncommon invar sword, and what do i get as a reward? his half brokken chestplate and 2 ender pearls that it...

either the herobrine raider need to be nerfed -> not as tanky, as he is hard enough to kill as it is
or
his rewards get a serious buff -> kinda like a boss battle when fighting a herobrine, which would be cool

**Comment by Darkosto** [comment]
Use a Soul Vial and it picks him up in 1 click.

**Comment by andr9528** [comment]
didn't get much time to do that... he was standing on top of my bed...

**Comment by andr9528** [comment]
also it seems that laser creepers still spawn regardless of light, just not as commonly as before because so many more raiders spawn now.

**Comment by andr9528** [comment]
have created another issue for the laser creeper thing

https://github.com/Darkosto/InvasionIssues/issues/121

**Comment by GenDeathrow** [comment]
tbh sounds  like RNG was not on your side.. as herobrine is a 1% chance to spawn, extra health depends on raid difficulty algorithm. normally 2.5 % / difficulty. I dint think adamentium is weighted high. as well as invar sword. he basically got lucky and got all the good stuff. its all random.   

As far as the loot, Its all based off vanilla drop standards.

**Comment by andr9528** [comment]
The herobrine had a diamond two handed sword, i had the invar sword.
