### ISSUE TITLE
[HQM]Cannot complete Power Cells quest

### ISSUE THREAD

**Issue by fairyhell** [Darkosto/InvasionIssues#122]
It's the quest require you to craft Furnace Generator, I did exactly what it says but the quest still not completed.

**Comment by Darkosto** [comment]
I just tested the quest and it works fine for me. Are you using the Extra Utils 2 Furnace Generator?

**Comment by fairyhell** [comment]
Yeah i used extra ultils 2 one. Crafted 2 but quest wasn't completed. I was playing on server btw.
