### ISSUE TITLE
Dungeontactics heart drop does not stack

### ISSUE THREAD

**Issue by andr9528** [Darkosto/InvasionIssues#123]
if a dungeon tactics heart drop, drop and is picked up by anything like an absorption hopper it  isn't used up and instead fil up the inventory as it doesn't stack , and is therefore hard to store if, one should chose to do so.

![2017-04-05_21 24 05](https://cloud.githubusercontent.com/assets/21788044/24723062/45083278-1a46-11e7-9f6a-3d8dae18790c.png)

**Comment by Darkosto** [comment]
It's not supposed to stack.
