### ISSUE TITLE
Wire Cutter Dupe

### ISSUE THREAD

**Issue by AtomCrusher** [Darkosto/InvasionIssues#124]
If you try to repair wire cutters they will dupe. Weird interaction with wire cutters trying to salvage wire cutters? Then dropping them on the floor and picking them up allows for stacking.
![2017-04-05_17 00 26](https://cloud.githubusercontent.com/assets/26940707/24726870/df9ffa70-1a21-11e7-9082-cf7bce2aa163.png)
![2017-04-05_17 00 37](https://cloud.githubusercontent.com/assets/26940707/24726877/e264a576-1a21-11e7-9667-1909a97ea37d.png)
![2017-04-05_17 01 00](https://cloud.githubusercontent.com/assets/26940707/24726883/e40250f4-1a21-11e7-8535-e64e7b2ed6a3.png)

**Comment by Darkosto** [comment]
Fixed in 1.0.6, thank you!
