### ISSUE TITLE
Invar Zweihandler can't be fixed in anvil

### ISSUE THREAD

**Issue by torres303** [Darkosto/InvasionIssues#125]
Don't know if it's a bug, but the game crashes every time i've tried to repair my invar Zweihandler. it happens with trying to repair it with ingots or another invar Zweihandler.

**Comment by vadis365** [comment]
This is an issue with the mod itself - could you please report it to the mod author.

**Comment by Darkosto** [comment]
Yep, for now use Duct Tape or the Item Repairer from Actually Additions.
