### ISSUE TITLE
Won't let me play?

### ISSUE THREAD

**Issue by RoyalTwo** [Darkosto/InvasionIssues#13]
So, I downloaded the modpack via Curse Client, and, when I launch it and make a new world, it won't let me click "Back to Game". It keeps me in the options menu, and won't let me click it. Any help?

**Comment by Kashdeya** [comment]
You will have to provide more info then just this. A crash log, console log, or anything for that matter other then it does not work.

**Comment by Darkosto** [comment]
No info given. Closing issue.
