### ISSUE TITLE
No Moon

### ISSUE THREAD

**Issue by Callum-MM** [Darkosto/InvasionIssues#130]
Finally managed to launch ourselves into space to find that the moon doesn't seem to exist. Playing multiplayer. Tried deleting the Luna dimension and letting it regenerate but it didn't fix it.
When we get there we can't move, Time itself seems to stop. I had a speed potion and when i got to the moon the timer stopped counting down. Got the achievement at least and the questbook location task completed but kind of wanted to build a space station at some point! xD
Using version 1.0.4

![themoon](https://cloud.githubusercontent.com/assets/14040343/24780438/42d14794-1b2f-11e7-9666-621a34e055d7.png)

**Comment by Yorkforce** [comment]
Just checked this too, the servers world/advRocketry folder doesn't have any of the DIM folders in it, also the temp.dat file is not listing any information. The SSP files have the correct DIM folder and temp.dat data it seems.

Edit: Sponge again, managed to figure it out and fix it though.

**Comment by Darkosto** [comment]
That's because there's no light.
