### ISSUE TITLE
Weird occurences...

### ISSUE THREAD

**Issue by Cucas360** [Darkosto/InvasionIssues#133]
I don't even know how to explain it... 
I entered my world the raiders were acting a bit odd: their arms and legs were all over the place and when I opened my inventory so were my arms and legs! 
Then I called in a medical supply which was interecepted by the enemy resulting in TNT falling. It destroyed some of my chests...

Now the weird part: 
I was fixing what the TNT had destroyed with dirt and I moved which suddently led to horizontal orange strips appearing in my screen (maybe something to do with the torches textures? The torches I had put down were the mini torches) and I moved again and got teleported to god knows where! I moved one more time and same thing happened plus my fps went down to 3! 

The game didnt crash and I don't know if this will help you with anything...

**Comment by Cucas360** [comment]
Ok I loaded a backup file from last night and THE SAME THING HAPPENED! I managed to get a screenshot this time and I think I know whats going on!
Its the raiders difficulty! Once I got the letters saying it had increased all this stuff started happening! Help please I love your modpack! 
And the movement bug was still happening it seemed like when I moved I started sprinting super fast!
![2017-04-08_19 45 55](https://cloud.githubusercontent.com/assets/24708748/24831577/401bab8c-1c94-11e7-8668-cf4e7ec12281.png)

**Comment by GenDeathrow** [comment]
have you added or changed anything to the pack?
try removing foamfix and see if that fixes anything? also make sure you video drivers have been updated(especially if its nvida).

**Comment by Ommina** [comment]
The arms & legs sounds a lot like #92 (where it was suggested to remove BetterFPS).

I can't even speculate on the second problem.

**Comment by Cucas360** [comment]
@GenDeathrow 
I didn't change anything in the pack no.

@Ommina 
You're a live saver! I think The second problem was caused by the 1st one I'm gonna remove it and i'll tell you something

**Comment by GenDeathrow** [comment]
@Ommina Thanks.. I couldn't remember which one it was.. it was foamfix or better fps, but I couldn't remember that one.
