### ISSUE TITLE
Obtaining Iron Plates???

### ISSUE THREAD

**Issue by ghost** [Darkosto/InvasionIssues#135]
So I've been trying to figure out how I can get Iron plates to start off with. The rolling machine requires iron plates to make. The IE plate presser needs steel, but the blast furnace requires nether bricks which require netherrack, which needs lava in a stone barrel, which you need a bucket for. You can't make the bucket without iron plates. I've been attempting to make use of the "Small Plate Presser" from Advanced Rocketry, and it looks like it's just a piston pushing into obsidian, but that doesn't seem to be working for me. Is it disabled in the pack?

**Comment by GenDeathrow** [comment]
Clay buckets > lava
