### ISSUE TITLE
Update, cant break blocks. Minecolonies

### ISSUE THREAD

**Issue by Liloa** [Darkosto/InvasionIssues#138]
So I updated the pack and apparently I cant operate where my base is because I do not have permission, used the supply ship before to steal the bed but then I never did anything after that. Is there any fix that I can do for this? Is there anyway to destroy the colony?

**Comment by GenDeathrow** [comment]
That seems like a question better meant for the mineconlonies github site.

**Comment by GenDeathrow** [comment]
https://github.com/Minecolonies/minecolonies

**Comment by Liloa** [comment]
Darkosto told me on stream just delete the mod and have it get updated and reinstall later. Probelem fixed...kinda.
