### ISSUE TITLE
Bottle of Tears destroys items

### ISSUE THREAD

**Issue by Kaelthalon** [Darkosto/InvasionIssues#139]
### Bug duplication:

Full inventory except for 2 spaces for bottle of tears and 1 space for salt.
Take the second bottle of tears on your hotbar, cry into it and cook it. Place it back into your inventory.
Cry into first bottle of tears, then immediately craft the first bottle of tears into salt.
A 'ghost' bottle of tears with a red 0 will replace the item in the slot before the first bottle of tears.

![2017-04-09_20 28 50](https://cloud.githubusercontent.com/assets/18230612/24843112/2165852e-1d65-11e7-914c-c213195e900e.png)
![2017-04-09_20 28 59](https://cloud.githubusercontent.com/assets/18230612/24843113/2169fd3e-1d65-11e7-8b6d-e13074bf68a8.png)
![2017-04-09_20 29 03](https://cloud.githubusercontent.com/assets/18230612/24843114/216c5bf6-1d65-11e7-801a-607fe7cf7f0f.png)
![2017-04-09_20 29 18](https://cloud.githubusercontent.com/assets/18230612/24843115/216c6088-1d65-11e7-8643-b9cebe1b9b11.png)
![2017-04-09_20 29 30](https://cloud.githubusercontent.com/assets/18230612/24843116/216c7a8c-1d65-11e7-8a25-d8c8e4da5cdb.png)

Note: During time of testing, I stood near a vacuum chest, which did not pick up any of the destroyed items.

I used slots 4 and 5 for the salt, slot 3 items were destroyed. I lost my Drill, then my bucket after doing a test. I've also lost several other items, but I don't recall what they were. I didn't realize the bug until now when something very valuable to me disappeared.

There's another bug that duplicates the bottle of tears, but I have yet to figure out how to duplicate that bug.

**Comment by WayOfTheQway** [comment]
Fixed in Crybaby 0.8 (I'm like 99.9% sure)
Hopefully the dupe is fixed too
Have fun crying
