### ISSUE TITLE
Crash in Creative Mode

### ISSUE THREAD

**Issue by Seanthebaker** [Darkosto/InvasionIssues#14]
Loaded up creative mode to have a look at the various mods in the pack, i had enabled hqm but when trying to go to the 3rd page of the creative menu the game crashes

log: http://pastebin.com/tA96JFfC

**Comment by Darkosto** [comment]
Yep, I came across this the other day. It looks like it's blaming Extra Utils. Hopefully, we can get this fixed up.

Thanks!

**Comment by Seanthebaker** [comment]
No problem!

**Comment by ReiannaWinters** [comment]
Any idea when this will be fixed?

**Comment by ReiannaWinters** [comment]
My Crash

https://pastebin.com/3nZCKXC7

**Comment by Darkosto** [comment]
It will be fixed when the mod causing the crash fixes the bug. For now, don't use the creative menu. It doesn't serve any purpose that cannot be fulfilled in another ways.
