### ISSUE TITLE
Crafting quests and their rewards

### ISSUE THREAD

**Issue by ImelchorI** [Darkosto/InvasionIssues#140]
some of the crafting quests could use a little bit of work in my opionion.

for example the crafting quest for the revolver makes us craft up all of the components for the item and then just gives us the completed thing as a reward.

its not the end of the world, but it feels a bit weird to now sit on the useless components that we made (not worth crafting them up into a second item either since it may damage or break the table).

instead the quest could just leave us with the components to finish the item, or require us to make a complete revolver and give us some more ammunition as a reward for example.

there are a couple more of these quests that do something similar. like the quest for the bride building gun.

**Comment by GenDeathrow** [comment]
The quest are as intended, the point is to find supplies.

Plus if you die, having backups is why you have a second.
