### ISSUE TITLE
EnderIO fluid tank and Cyberware

### ISSUE THREAD

**Issue by HellEye** [Darkosto/InvasionIssues#141]
Crafting treated planks with an EnderIO fluid tank consumes the entire tank. Not just liquid, the item. Not sure if it's modpack or the mod itself. Easy fix is disabling the crafting recipe that uses the tank. It's annoying to click the buckets all the time though, it'd be a huge time saver to have this feature working. 
Update: weird thing, that recipe isn't even in JEI... but it's in the game. Super weird. Here go screenshots!
![image](https://cloud.githubusercontent.com/assets/3741381/24873796/86f79612-1e22-11e7-850b-94ee8269ba1c.png)
![image](https://cloud.githubusercontent.com/assets/3741381/24873802/8e19b290-1e22-11e7-8239-d6ff1d1a1e34.png)
![image](https://cloud.githubusercontent.com/assets/3741381/24873813/93e300dc-1e22-11e7-9802-d1f0c46ff0db.png)
My guess would be something about that recipe says it's the same as clearing the fluid out of the tank by crafting it. But then you get the tank back and here you get planks... 
Disclaimer: two tanks lost lives while figuring out the fact that it's a bug. RIP tanks. 

Second thing, not really a bug, maybe I'm just not seeing something but... Can you do anything with cyberware? Raiders only seem to drop the base human organs and to craft anything myself I need cyber eyes for the scanner thing... Can they be found somewhere in chests or during a quest later down the line? I never used the mod before and wanted to give it a try here. Suggested fixes (assuming it's not just me): cyber eyes as a rare dungeon loot, craftable with a fair price, changing scanner recipe to use a block of diamonds or something like that. Or just fix the drops. Though I'm guessing there's a reason for disabling them in the first place.

**Comment by GenDeathrow** [comment]
Best to make two issues, having more than one in an issue sometimes makes it hard to track and can get overlooked. As far cyberware >> https://github.com/Flaxbeard/Cyberware/wiki/Getting-Started you can use your own body parts. 

I will let someone else answer the other question.

**Comment by Darkosto** [comment]
There's no fix needed for Cyberware since the pack already has an entire quest line and drops configured for the mod.

**Comment by HellEye** [comment]
Ooh okay, yeah I'm dumb then. I completely overlooked the automation tree in my playthrough and that's what unlocks cyberware. Still the creosote tank issue remains. Just disable the recipe I guess since it's not in JEI anyway.
