### ISSUE TITLE
Little Looter Orbital drops are empty

### ISSUE THREAD

**Issue by tali713** [Darkosto/InvasionIssues#144]
What it says on the tin.  Have had this happen on two worlds now, after a while orbital drops are empty, not sure what triggers the bug, relogging and restarting do nothing.  If this is as intended, it is undocumented.  Makes it difficult to get resources.

**Comment by GenDeathrow** [comment]
https://github.com/Darkosto/InvasionIssues/issues/128#issuecomment-293047542

**Comment by GenDeathrow** [comment]
https://github.com/Darkosto/InvasionIssues/issues/68

**Comment by Darkosto** [comment]
Reinstall the modpack.
