### ISSUE TITLE
Tilled Land Issue

### ISSUE THREAD

**Issue by maxes195** [Darkosto/InvasionIssues#145]
When you jump on tilled land turning it to dirt you get stuck in the block and are not able to jump off the block, the only way out I've found is breaking the land or walking out slowly to a side that doesn't have any blocks
![image](https://cloud.githubusercontent.com/assets/27309510/24930966/b1676368-1ec8-11e7-986b-e67431350d23.png)

**Comment by Darkosto** [comment]
That's a vanilla bug, not a modpack bug.
