### ISSUE TITLE
Space Travel Multiplayer Issues

### ISSUE THREAD

**Issue by Gorehid** [Darkosto/InvasionIssues#147]
I had one of my players report this problem to me on 1.0.4. It seems there is no moon, nor any celestial bodies.
I set up the things needed to go to the moon. [The rocket ](http://imgur.com/a/VNfy8)with the chip inside. Me sitting on the [rocket with the destination of Luna.](http://imgur.com/a/knKO6) After launching the rocket and moving through the loading screen you end up with the[ pictured.](http://imgur.com/a/C9Ybf)

**Comment by GenDeathrow** [comment]
Its just dark "Hardcore darkness"

Actually your height is still at 1000, did you actually land?


https://github.com/Darkosto/InvasionIssues/issues/130

**Comment by Yorkforce** [comment]
Sorry to butt in, are you using SpongeForge Gorehid?

If so the server.properties setting of allow-nether=false will prevent multiworlds from being created in sponge, there is a solution by enabling and using dimension configs in the sponge config folder to disable the nether and the end that way and allow the allow-nether=true settings without disrupting the modpack settings.

Unfortunately there is also a crash problem with Advanced Rocketry world gen and possibly sponge so we might need to wait for Invasion 1.0.5 if Darkosto is updating the Advanced Rocketry mod in the next version.
Issue is reported here: https://github.com/zmaster587/AdvancedRocketry/issues/529

**Comment by Gorehid** [comment]
No, I could not actually land. It gets to that spot in the process and stalls there. No actual planet or, in this case, moon shows up. I have found no reason for it doing so, but there it is. If I'm missing something obvious I'd be delighted to learn it, GenDeathrow.


Thank you for responding, Yorkforce. However, I am not using SpongeForge. This is a "plain" Invasion server.

**Comment by Yorkforce** [comment]
Ahh ok, what you described sounded almost exactly what we had which is why I mentioned it, hope you get it sorted :)

**Comment by GenDeathrow** [comment]
@Gorehid Normally when you spawn in with Advance rocketry you hit space bar to land, but words will pop up on the screen to tell you that.At a 1000 blocks up nothing will render so you wont see the moon. but as you get closer to your render range you will see the moon sort of, its super dark. redstone lamps, and redstone torches emit light. 

Here is the part of the stream where dark got to the moon. 
https://www.twitch.tv/videos/134062123?t=05h33m43s

**Comment by Gorehid** [comment]
@GenDeathrow I do understand what you are saying, truly. I am however saying that is not the issue. I have gone to the moon in single player, yes it is dark, but you can get there. What I and other players on my server are experiencing is different. The rocket you are riding appears to no longer exist after going through the loading system. You stop in place and can hit no buttons to do anything. It's not that the moon is dark it's NOTHING exists after the load. Be it a space station you created or the moon. Now, this may be a specific issue with my server and nothing can be done about it. I do not know about that, but I am reporting it here in case it is not just us.

**Comment by GenDeathrow** [comment]
That explains its a lot better. Which is why I have to ask questions like that. Its like computer customer server asking if your computer is plugged in.
 
As far as the issue, you right it may be a local issue. I couldn't find anything on the [Advance Rocketry Issue Tracker](https://github.com/zmaster587/AdvancedRocketry/issues?page=3&q=is%3Aissue+is%3Aopen). but my suggestions is create an issue on Advance rocketry tracker and link this. See if they have insight as I don't think we have come across this issue yet.

**Comment by Elvarion** [comment]
Can confirm that this is an Issue.

Hosted a normal Invasion server for me and some friends. We are also experiencing this.
Everyone built their own rockets. We launch and after the loading screen nothing happens. We are stuck on the exact coordinates and that is it (So no descending towards the moon).
You can even launch into space without a space suit and it wont kill you since nothing really happens after the loading screen.

Singleplayer is working just fine.

**Comment by GenDeathrow** [comment]
Mod other can't replicate it and neither could we do closing the issue for now.

**Comment by eaanon01** [comment]
I have the excact same issue on 1.05 and 1.07. You go to the moon the dimmension loads and you are stuck at 1000 blocks and no spash screen asking you to assend or any form of countdown.. Spacebar does nothing. Please let me know if you want access to diganose the problem. Singelplayer ok multiplayer not ok.

**Comment by zmaster587** [comment]
I think I found an explaination here: https://github.com/zmaster587/AdvancedRocketry/issues/555#issuecomment-302229632

**Comment by Yorkforce** [comment]
For anyone else wondering and running a sponge server, you can do the following:

server.properties: allow nether=true
config/sponge/worlds/minecraft/nether dimension.conf: config enabled=true and world-enabled=false
config/sponge/worlds/minecraft/the_end dimension.conf: config enabled=true and world-enabled=false

That will properly disable The Nether and The End but allow multiple worlds such as space dimensions.

**Comment by eaanon01** [comment]
Thanks! But I do not have any sponge configs in my server... ?!?

**Comment by Yorkforce** [comment]
If you don't run sponge I don't think there is a lot you can do unfortunately, other than enabling the nether and the end.
