### ISSUE TITLE
Cyberwabe Hud

### ISSUE THREAD

**Issue by Treachours** [Darkosto/InvasionIssues#148]
Hud from Cyberwabe is not showing up on the screen. i tried to move it , change colour... nothing happen.
Problem is i acnt see the energy i have left then my eyes stop wworking and i get full blind ^^ be carefull whit that

**Comment by GenDeathrow** [comment]
Did you remove your eyes in the Robosurgeon? cause that gives you blindness, just like if you remove your arm you cant click, or your legs you can only hop.  You have to have the parts to replace it all.

**Comment by Darkosto** [comment]
If I'm not mistaken, that's because you need to install the HUD part to see it.

**Comment by Treachours** [comment]
i have the battery installed and the hud upgrade 
and yes i removed my eyes ,u just cant do it if u dont remove it
i made a creative world just to test it and the same happen

**Comment by Darkosto** [comment]
Right, because you need the HudJack and other items to display the info.

**Comment by GenDeathrow** [comment]
there is a possibility that it deals with this issue. https://github.com/Flaxbeard/Cyberware/issues/101

**Comment by Darkosto** [comment]
Fixed in 1.0.6
