### ISSUE TITLE
Recipe Guide Crafting Table v1.1

### ISSUE THREAD

**Issue by Kaelthalon** [Darkosto/InvasionIssues#150]
Hey, I noticed you closed my topic regarding the Recipe Guide Crafting Workbench, but that's still an issue in the modpack. From my understanding, Darkosto wants the EnderIO Inventory Panel to be the only infinite crafting method. My apologies for mixing two problems with the same item.

**Comment by Darkosto** [comment]
The recipe guide crafting workbench from WTF-Expedition? I'm 99% certain it shows you recipes, it doesn't allow crafting operations.

**Comment by rjwboys** [comment]
don't know if i should put this here or not move this if needed

i see in the config file for WTF that this is set B:"Enable Crafting Recipe Table"=false
but recipe guide crafting table still appears in loot and it crashes the client when used

**Comment by GenDeathrow** [comment]
It's already been reported to the mod dev. That's for reporting.

**Comment by Darkosto** [comment]
Should be removed from obtaining in 1.0.6
