### ISSUE TITLE
[Improvement] Longevity after completing quest book.

### ISSUE THREAD

**Issue by HiImWren** [Darkosto/InvasionIssues#151]
After playing the mod pack and reaching the end of the quest-book I encountered two things that felt really, off. raiders spawn on other planets, and no ores spawn on other planets. these two things for me really took away the feeling of accomplishment of reaching Luna and also deeply broke the immersion of the mod pack. for some people, that is fine they simply take pride in beating the quest book and move on, but for me I wanted to continue playing after the end of the book. I modified my config files to spawn ore on other planets, [here](https://pastebin.com/Mmt353TG) is the XML code I used in config\advRocketry\oreConfig.XML to accomplish this: feel free to utilize or modify this code in any way you feel fit. I believe it will make the pack better for those who just can't say goodbye to their worlds. I wasn't able to get the raiders to only spawn in the over world as the config lacks the options for non-vanilla dimensions.

**Comment by Darkosto** [comment]
Thank you for figuring out how to do this. I've been putting it off for so long and you saved me a ton of time xD

I'll try and get this in for 1.0.5 update. Just waiting on 1 mod to update to fix a bug and the update will be public :)

**Comment by HiImWren** [comment]
A couple of things about configuring it I couldn't get titanium to spawn because it appears to be a different meta-data of libvulpes' ore0. I set it to spawn crafting tables on other planets as a quick and easy workaround for not using the enderio inventory panel, and for convenience. I set it to gen different ores on different planets based on the the pressure value, additionally you can create even more cases using the temp="{0-5}" if you want even more cases. Obviously for controlling raider spawns it wouldn't be difficult to add a config option to white-list the Dim Ids that raiders spawn in. you appear to be pretty close to GenDeathrow so should I leave it to you to contact him or should I just slap an issue on the raiders GitHub?

**Comment by HY-Leung** [comment]
Just got every kind of ore from void ore miner by @env. tech

**Comment by Darkosto** [comment]
Finally able to get to this and implement it. The issue you had with Titanium ore was not specifying the meta data. Here is the correct line:

        <ore block="libvulpes:ore0" meta="8" minHeight="1" maxHeight="16" clumpSize="8" chancePerChunk="16" />

Will be in for 1.0.6
