### ISSUE TITLE
Souldbound Enchant 

### ISSUE THREAD

**Issue by Treachours** [Darkosto/InvasionIssues#153]
Well there 2 types of Souldbound enchants in the game, i dont know the name of the mod but that one that gives xp to the weaopns and extra skills,that sould bound work great,But the normal soulbound enchant dosnt work(the one u get by normal enchanting)in fact if u have the normal soulbound in ur tool and u die,you wont get it back when u die and it wont be inside ur grave,it just dissapear.

So normal vanilla enchant make ur items dissapear after dead
 Srry for my english just trying to help

**Comment by LuciousLisa** [comment]
I can confirm this. Lost my level 5 legendary strong diamond crossbow this way. :'(

**Comment by Lurmey** [comment]
I haven't got far enough to experience this in my game, but Soulbound isn't a vanilla enchantment, it's added by EnderIO as far as I know. Perhaps this should be reported as an incompatibility between Levels and EnderIO.

**Comment by Darkosto** [comment]
This has been remedied in, honestly, the only way possible for where we are in the pack: Soulbound has been removed. There's no way to get it working with the levels mod currently, and the levels mod is too integral to the modpack.
