### ISSUE TITLE
Mods that are just there.

### ISSUE THREAD

**Issue by Mattyzz** [Darkosto/InvasionIssues#154]
Now that i'm at a stable point in the pack I've found that there are many mods that just seem to "be there". There's no quest line that introduces them. Some mods are **Advanced Generators**, **Minecraft Flight Simulator** and **Quantum Flux**. I'm wondering if there are plans to introduce them in the pack through quest lines and such.

**Comment by Darkosto** [comment]
Not every mod is going to have a quest line. Those mods are there for multiple options for the player to use if they want. Not every player is going to play the same, even on multiple playthrough. This gives more content to try out.
