### ISSUE TITLE
I'm an Idiot who feels the need to act like a child.

### ISSUE THREAD

**Issue by asdan1** [Darkosto/InvasionIssues#156]
DAY 70 STILL ONESHOTIN FAM

*Edit You can all have a go on my mother as she said it would be fine. Even 2 or 3 at a time.

**Comment by vadis365** [comment]
I have no idea what you are even talking about. If you have an issue to report please use clear and concise English without offensive language. You have unfortunately not done either of these things and therefore warrant us to either block you or report you to github and have your account cancelled.
