### ISSUE TITLE
Placed Airdrops disappear

### ISSUE THREAD

**Issue by MalContentFL** [Darkosto/InvasionIssues#158]
After I put my items in airdrops which I place, I went off adventuring. I died and when I got my stuff and returned home the airdrops were done. Could it be a chunk unloading bug?

**Comment by MalContentFL** [comment]
I just figured out all airdrops disappear over time (about 5 min). If its an intended feature I don't like it, but player-placed ones should not despawn.

**Comment by Surg-Dev** [comment]
All airdrops disappear, no matter what. I recommend not using them as chests (get iron anyway!) You could ask the developer of "Little Looters" but I doubt you will get anywhere (aka Darkosto)

**Comment by GenDeathrow** [comment]
Because the airdrops have particle effects, they disappear after a while so too many don't cause low fps.

And so the world isn't littered with airdrop everywhere
