### ISSUE TITLE
Duplication of Iron, Gold, Diamonds, and Emeralds.

### ISSUE THREAD

**Issue by RihnZaevruhn** [Darkosto/InvasionIssues#159]
I don't see anything about this being found yet so I'll post this here. I found a way to easily duplicate iron and gold by crafting armor then scrapping them with wire cutters and using a pulvus. A chestplate costs 8 ingots to craft. Using wire cutters on it gives you enough ore pieces to craft 5 chunks which doubles to 10 ingots in a pulvus. You get even more if you use a sag mill with dark iron balls and can easily turn a small amount of iron or gold into a few stacks as long as you have extra fuel and crafting tables. 

Diamonds and emeralds are an even worse case since you just have to put them in a sag mill with dark iron balls to easily duplicate them. You can even have the sag mill and alloy furnace feed into each other to create an infinite loop until it runs out of room. This works as long as you keep the sag mill stocked with dark iron balls.

**Comment by Darkosto** [comment]
Changed in 1.0.5
