### ISSUE TITLE
Nether quartz from hammering is unusable

### ISSUE THREAD

**Issue by Zaecus** [Darkosto/InvasionIssues#16]
The nether quartz you get from hammering andesite/diorite/granite is item number 406:1 and cannot be used in _any_ recipes.

Or... at least... the quartz I get is.

**Comment by Zaecus** [comment]
To reproduce: Hammer diorite/andesite/granite with an iron hammer with no quartz in your inventory.

An in game fix, if you can get quartz another way is to stack the bugged quartz with non-bugged quartz. It loses the ":1" and becomes normal quartz.

**Comment by Darkosto** [comment]
Just those stone types? Weird, I must have left meta data in them by accident. I'll fix this up today.

Thanks!

**Comment by Darkosto** [comment]
Fixed in 1.0.1
