### ISSUE TITLE
Sand, clay and stone structures growing in underground base

### ISSUE THREAD

**Issue by vaptsiukas** [Darkosto/InvasionIssues#161]
Moments ago duplicated what I think is an issue. [link](http://imgur.com/a/PGn8J) to screenshots, where you can see red sand tiles grown randomly even on torches, some stone stalagmintes has grown in corner and in the stairway to surface (stairs not in the picture). Even some smooth stone is changed to red sandstone in walls, some random cobblestone generated instead of smooth stone.
This happens sometimes when you save the world, exit the game and after some time go back to the same save. Then you find these structures (blocks) appeared from somewhere.

Is this intended or I'm just don''t know something about biomes mechanics? This happened to me in Outback biome.

**Comment by GenDeathrow** [comment]
https://github.com/Darkosto/InvasionIssues/issues/86 < reported here Deals with WTF Expedition.
