### ISSUE TITLE
Missing textures on Invasion mod

### ISSUE THREAD

**Issue by frenchiveruti** [Darkosto/InvasionIssues#162]
So, I have no idea what the blocks are, but I'm using linux, used Vazkii's modpack downloader, and using MultiMC with the latest Forge Version 12.18.32281.
![2017-04-15_10 40 32](https://cloud.githubusercontent.com/assets/1095997/25064077/26df611a-21c9-11e7-9be2-80ed0450e0c6.png)
Thanks

**Comment by Surg-Dev** [comment]
Try giving yourself "The One Probe" just to see what block it is and get back to us?

**Comment by Ommina** [comment]
I'm almost certain you do not have the WTFExpedition ("Do No Disable") resource pack loaded.

**Comment by Darkosto** [comment]
Yep, you have the WTFExpedition resource pack disabled. It comes auto-enabled in the pack. Turn it back on.

**Comment by frenchiveruti** [comment]
ok thanks!
