### ISSUE TITLE
Heart of Gold issue?

### ISSUE THREAD

**Issue by Surg-Dev** [Darkosto/InvasionIssues#163]
Heart of Gold bottles really confuse me, so much so that I can't figure out whats intended or what is not intended, so let me list what happens with my hearts of gold (health expansion, not the item):

Sometimes I take damage from a source and it just disappears (Instead of being restore-able)
Sometimes I randomly take damage and it disappears (assuming this is normal)
When I log out and log back in it disappears. (Possible bug)

Can someone clarify and tell me what is a bug/intended?

**Comment by GenDeathrow** [comment]
They are temporary health not permanent.  Its possible logging out and back on is a sort of bug if they aren't saving it.

**Comment by Darkosto** [comment]
The quest book actually describes this as being a temporary boost of health. When the health is taken away by damage, it's gone.
