### ISSUE TITLE
Placing Propeller Bench crashes user out of world

### ISSUE THREAD

**Issue by Mipolo** [Darkosto/InvasionIssues#166]
Issue is as described in the title.

**Comment by GenDeathrow** [comment]
crash log?

**Comment by Darkosto** [comment]
https://bitbucket.org/don_bruce/minecraftflightsimulator/issues/33/crash-kicked-from-world-when-placing

**Comment by vadis365** [comment]
Could always remove the planes and re-enable jetpacks and jetpack spiders :P

**Comment by Darkosto** [comment]
This mod has been removed because the author won't fix it. Sorry!
