### ISSUE TITLE
Infinite Torches?

### ISSUE THREAD

**Issue by TreasureHunterHD** [Darkosto/InvasionIssues#167]
Only if you have coal. 1 stick makes 4 torches, and 1 torch can be broken down to make 1 stick, allowing you 4 more torches. I can turn one stick into 100 torches. Is this intended?

**Comment by Ommina** [comment]
I admit it seems a bit odd.

On the other hand, if there is one phrase that I've never uttered while playing this pack, it is **not** "If only I had more sticks".

**Comment by Darkosto** [comment]
I'll just remove this recipe in 1.0.5
