### ISSUE TITLE
Worldgen sphere caves and structure generation.

### ISSUE THREAD

**Issue by Zahkriiven** [Darkosto/InvasionIssues#168]
This is more of a config issue and might be addressed client side.
I was starting to play the pack when found these spheres caves kind of thing are way too common that they destroy de landscape, and sometimes break other world and structure generation. Screenshots below. 
![2017-04-17_00 05 43](https://cloud.githubusercontent.com/assets/25531677/25074812/5cf6a7a8-2305-11e7-90db-3f34361a4c4a.png)
![2017-04-17_00 03 31](https://cloud.githubusercontent.com/assets/25531677/25074819/70585bca-2305-11e7-9d3e-5f93f90aa75f.png)
![2017-04-17_00 03 56](https://cloud.githubusercontent.com/assets/25531677/25074821/751099de-2305-11e7-9de4-70589a089307.png)
![2017-04-17_00 09 45](https://cloud.githubusercontent.com/assets/25531677/25074826/83998cfe-2305-11e7-8618-d4c229cd0bc3.png)
In addition, i also found the structure generation rate quite high too, sometimes they are two structures just side by side and you can always spot one at the distance from another one. Screenshots below.
![2017-04-17_00 07 32](https://cloud.githubusercontent.com/assets/25531677/25074852/0cd8d3f8-2306-11e7-9e13-32d659ec63ad.png)
![2017-04-17_00 38 18](https://cloud.githubusercontent.com/assets/25531677/25074856/2e29cf3a-2306-11e7-97e7-07cdbc6c9393.png)
![2017-04-17_00 12 59](https://cloud.githubusercontent.com/assets/25531677/25074857/3232feee-2306-11e7-9d61-997bb38e15ea.png)
Final screenshot of the map.
![2017-04-17_00 29 06](https://cloud.githubusercontent.com/assets/25531677/25074865/5dec50e4-2306-11e7-9cc3-fdbb39269552.png)
 I would really apreciate some indications if i can tweak this myself as i don't know which mods add all this. 

Sorry for the large post and thanks for the hard work.
~Zahkriiven

**Comment by GenDeathrow** [comment]
The sphere's are intentional since the pack is based on a world where other players and mined out the world out. But Structure & the sphere are also based on the random seeds. some seeds generate a lot and others don't.  "Quark and Recurrent Complex"
