### ISSUE TITLE
Client/Server (SSP) Crash (v1.0.4)

### ISSUE THREAD

**Issue by Lost-Ninja** [Darkosto/InvasionIssues#171]
Both of these happened as far as I can recall while moving items around in my inventory. I also suffered forced disconnect in the time between the two (dropped me out of SSP into the server select menu) (no logs/crash report for that however...)

1st Crash: https://pastebin.com/a1R3tLJ2

2nd Crash: https://pastebin.com/yed1cUE0

**Comment by Lost-Ninja** [comment]
Just checked my recording, 2nd crash happened while breaking a cacti with a sword. I'll try and track down the recording of the first to confirm the circumstances...

**Comment by Lost-Ninja** [comment]
Just starting up the game again and crash no3:
https://pastebin.com/dNb6tjBf
Happened on game launch. Loading save game made after crash 2 above ( so Crash 2 >> Restarted game >> Played Save >> Saved/Quit >> Relaunched >> Start Save >> Crash 3).

**Comment by Darkosto** [comment]
What world type are you using on the server?

**Comment by Lost-Ninja** [comment]
Biomes of Plenty - Just a standard launch no options changed then elevated to LAN.

**Comment by Darkosto** [comment]
That's a really strange issue :/

Does it happen on every world?

**Comment by Lost-Ninja** [comment]
One world so far, just this one in fact. Normally wouldn't care too much... modded minecraft does crash, but I was recording a 'lets play' so it's a bit more annoying than normal.

Apart from the difficulty ramp (even on easy) you've done an amazing job on this modpack (IMO) so I'm happy to put it down to 'one of those things...'.

The save is 29Mb, if I can find somewhere to upload it I will if that should help you work out what is going on. :D

**Comment by Lost-Ninja** [comment]
Suddenly occurred to me... dropbox... :/

https://www.dropbox.com/s/k587h0dixy8vqra/Lost%20Invasion%20-%20Madness___.7z?dl=0

**Comment by Darkosto** [comment]
Can you try the world out with the new 1.0.5 update I posted yesterday? Might not help, but could be a place to start. I'll take a look at this world save you sent and see what I can figure out. Thanks for sharing!

**Comment by Lost-Ninja** [comment]
Will do.
