### ISSUE TITLE
Hardened blocks (Tier 1) Causing Ghost blocks

### ISSUE THREAD

**Issue by Brent757** [Darkosto/InvasionIssues#172]
Every time I break a hardened block (Tier 1), it breaks instantly with anything, and creates a ghost blocks for me, This is on a server where i am infinitely falling into a ghost block, even when I re-log.

**Comment by Darkosto** [comment]
Cannot reproduce.

**Comment by Ommina** [comment]
This should probably be reported to open modular passive defenses.

The hardened blocks (any tier) have an owner.  The owner (the player who placed it) can remove them via a crouch-right click with an empty hand.  Other players are not supposed to be able to remove them.

However, on a server at least, other players (or the owner, with a tool) can 'remove' the block, but it happens on the client only.  Thus the ghost blocks experienced above.
