### ISSUE TITLE
Insane console spam 1.0.5

### ISSUE THREAD

**Issue by Yorkforce** [Darkosto/InvasionIssues#174]
Just updated to 1.0.5 and we are seeing this in the console every second:
18.04 03:25:48 [Server] INFO baserf:20----TicksNeeded:400
18.04 03:25:48 [Server] INFO baserf:20----TicksNeeded:400
18.04 03:25:48 [Server] INFO baserf:20----TicksNeeded:400
18.04 03:25:48 [Server] INFO baserf:20----TicksNeeded:400
18.04 03:25:48 [Server] INFO baserf:20----TicksNeeded:400
18.04 03:25:48 [Server] INFO baserf:20----TicksNeeded:400
18.04 03:25:48 [Server] INFO baserf:20----TicksNeeded:400
18.04 03:25:48 [Server] INFO baserf:20----TicksNeeded:400
18.04 03:25:48 [Server] INFO baserf:20----TicksNeeded:400
18.04 03:25:48 [Server] INFO baserf:20----TicksNeeded:400
18.04 03:25:48 [Server] INFO baserf:20----TicksNeeded:400
18.04 03:25:48 [Server] INFO baserf:20----TicksNeeded:400
18.04 03:25:48 [Server] INFO baserf:20----TicksNeeded:400
18.04 03:25:48 [Server] INFO baserf:20----TicksNeeded:400
18.04 03:25:48 [Server] INFO baserf:20----TicksNeeded:400
18.04 03:25:48 [Server] INFO baserf:20----TicksNeeded:400

Never seems to end, any idea what could causing this? as we do rely on console to check for errors and logs.

**Comment by wallofchaos** [comment]
Same issue. Server logs over a gig now. =\

**Comment by liorrozen** [comment]
For me it seems that placing the cell analyzer from genetics reborn starts these logs lines - breaking it stops the log output.

**Comment by TheUnderTaker11** [comment]
Should be fixed in newer version of Genetics Reborn.

**Comment by Darkosto** [comment]
Added in 1.0.6 of Invasion and should be all good now!
