### ISSUE TITLE
Typo in "Bob The Builder" quest.

### ISSUE THREAD

**Issue by Amoa123** [Darkosto/InvasionIssues#175]
In the quest named "Bob The Builder" (in chapter 5), at the end of the quest text it says; "This should be the second building you place after **you** Town Hall so you can **have** hire builders to help you grow your colony." (Bolded to show errors)

It should read "This should be the second building you place after your Town Hall, so you can hire builders to help you grow your colony."

**Comment by Darkosto** [comment]
Fixed in 1.0.6, thank you!
