### ISSUE TITLE
Invasion 1.0.5 - Healing Salve Recipe... Undocumented Change or Bug?

### ISSUE THREAD

**Issue by ArcaniX5696** [Darkosto/InvasionIssues#176]
Started up a new playthrough (rather than deal with the quest fix stuff) and noticed that Healing Salve is suddenly: a bowl, a seed, a cactus, a poppy, a dandelion and a vine??  No healing salve recipe changes in the changelog so assuming this was unintended?  (I hope so!!)

![image](https://cloud.githubusercontent.com/assets/26642873/25115555/2be08e42-23d5-11e7-8c8c-a3223a295212.png)

**Comment by Darkosto** [comment]
Oh interesting, somehow it overwrote my custom recipe. That's... strange. I'll get that fixed up. 

Does this persist through a pack reload?

**Comment by ArcaniX5696** [comment]
I'm not sure what you mean specifically - I had 1.0.5 installed to it's own folder and did not transfer my save.  This is the recipe for 1.0.5 fresh install.

If you can clarify what you mean by "pack reload", I'll happily test it out for you and report back.

Regards,

**Comment by ArcaniX5696** [comment]
OK, this is *really* strange.

When I re-loaded my game yesterday, there was no change in the recipe.  Although there have been no updates to the pack since yesterday, I'm *dying* to get back to my playthrough so I fired it up again tonight... ...and... the recipe is back to a bowl, two seeds and a sapling.

I have no idea what may have caused this, but I seem to be OK again.

Please feel free to dismiss/close this, unless you'd like me to try and figure out the steps to re-create - let me know.

Oh!  and thank you for taking the time to breathe fresh fear into Minecraft!  :)
