### ISSUE TITLE
Soulbound Tier 3 backpack dup bug

### ISSUE THREAD

**Issue by QuestionSleep** [Darkosto/InvasionIssues#177]
When I died, I re-spawned with my backpack(pack-1), all is well. However there was a second pack that was identical with identical items(pack-2). Took some stuff out of pack-1 and items from pack-2 would disappear but take some stuff out of pack-2 and it would still be in pack-1. Basically pack-2 is a static copy of pack-1, whatever pack-1 has, pack-2 has. Take something out of pack-1 and pack-2 no longer has it. Anytime pack-1 is opened it will set pack-2 as what is inside pack-1.

**Comment by DetMiner** [comment]
This happened to me as well, however if you die again with the 2 backpacks you'll have 4 on respawn. The items in backpacks 3 and 4 can be taken out without affecting backpacks 1 and 2, basically duping the items.

**Comment by Darkosto** [comment]
Fixed in 1.0.6 by removing newly created soulband bags. I cannot, however, remove already created ones.
