### ISSUE TITLE
1.0.5 - Mobs spawning issue

### ISSUE THREAD

**Issue by Kelmey** [Darkosto/InvasionIssues#180]
The was a clean install on a new world for 1.0.5. MP server with three players.

I guess this may not be a bug but I feel it is different than before.

Mobs started spawning immediately on day 0. I thought mobs are not supposed to spawn until the first night.

During day 1 there were constant mob spawns. No we were not crafting hardly anything since it took the three of us constantly fighting to not get overwhelmed. Raiders were spawning in groups up to 9. Several time there were over 30 mobs attacking at a time.

**Comment by GenDeathrow** [comment]
you sure the configs got correctly downloaded?

**Comment by Kelmey** [comment]
Well the server download is a zip, so if it failed to download correctly I wouldn't be able to open the zip file. I guess I can try it again tonight. Although I'm thinking of trying 1.0.4 since several let's plays I've seen has shown less mobs on that version.

**Comment by GenDeathrow** [comment]
I can tell you spawns haven't changed at all in those versions. I've noticed some worlds just have more spawns. Also  your not suppose to get any mob spawns on day 0 unless they are  below Y level 60 or as soon as night shows up.

**Comment by Kelmey** [comment]
There was an enormous crater near spawn. Maybe it was below Y 60. 

I'll download fresh copies of the server and spin up another server tonight and see if I get anything different.

**Comment by Kelmey** [comment]
Also, do more mobs spawn if there are more players in an area? Three of us were trying to play together so if that causes extra spawns then maybe that was it?

**Comment by GenDeathrow** [comment]
Yes more mobs spawn with more players. That's actually vanilla mechanics not easily controllable
