### ISSUE TITLE
1.0.5 - Feature request - option for an easier game mode

### ISSUE THREAD

**Issue by Kelmey** [Darkosto/InvasionIssues#181]
This mod sounds great. But for my friends it is too hard. We've tried version 1.0.1, 1.0.2, and 1.0.5. Every time we give up after realizing we can't go through the quests fast enough to get enough tech fast enough to keep up with the scaling difficulty. 

It would be awesome if setting the game ti easy difficulty would make the game noticeably easier. Fewer mobs, lower spawn rate, etc. 

If that is not possible a set of alternate configs that lowers difficulty would be awesome.

**Comment by st753m** [comment]
There is a config option for slowing down raid progression.  Go to the config > raiders > settings.cfg and alter "Raid Day Difficulty Progression" to something higher than 8.  That file has other things you can tweak too.
