### ISSUE TITLE
cyberware hud not working.

### ISSUE THREAD

**Issue by ImelchorI** [Darkosto/InvasionIssues#185]
so i managed to get my hands on a pair of cyber eyes from the quest book, and a hudjack plus a target overlay from utility crate drops.

installed all the components including the internal battery from the quest book.

however, i seem to have a problem to get the cyberware hud to work. knowing the internal power storage would be incredibly useful.

i do have enough power to run the eyes themselves (made a charger and installed multiple internal generators). i know this because the other implants seem to be working fine, and the target overlay (which needs the hudjack as a requirement) is actually working and displaying mobs through blocks. i can enable and disable the function at will via the wheel menu.

its just the hud, including the power info that dosnt seem to be working. i tried going into the cyberware hud config to move around the elements since i expected that theyre possibly covered by the minimap or other interface elements in this modpack. but its not helping. (checked that theyre set to display aswell, and they arent set to be hidden.).

any advise?

edit.: i did another test in a 1.10.2 world with just the cyberware mod installed (same version). the hud displayed as it should. so it seems to be an issue specific to this mod pack.

**Comment by GenDeathrow** [comment]
Already reported
https://github.com/Darkosto/InvasionIssues/issues/148

It'd more a mod interaction.

**Comment by Darkosto** [comment]
Fixed in 1.0.6
