### ISSUE TITLE
request- easier progressive automation cobblegen upgrade recipe

### ISSUE THREAD

**Issue by syilphia** [Darkosto/InvasionIssues#186]
i don't check on latest release yet, so forgive me if i wrong but,
cobble gen update need you to make it using iron bucket, which is not easy to get, compared to that, ExU2 mining upgrade doesn't need that, you can make it as early as day 3. 
Considering how PA miner work, my suggestion is to make the cobblegen upgrade cheaper, or just easier to get without delving to much on the tech line (because it's can't be automated)

**Comment by ImelchorI** [comment]
cobble gen is easier to accomplish with extra utilities transfer nodes. you need some extra utils solar panels to start (9 panels suffice), and a resonator to craft the mining upgrade. the item transfer nodes themselves are cheap. just google how you make the extra utils cobble gen and look up the recipes in NEI.

remember that the node is going to take grid power once its running while it has the upgrade installed. if you overload your grid by having it run at the same time as the resonator with only those solar panels, all extra utilities machines will stop working. even those that dont draw grid power themselves. (like extra utils rf generators without upgrades)

if you dont use the resonator, or more grid power other than for the cobble gen, the solar panels should suffice.

for more cheap and easy grid power, look at extra utilities water mills.

**Comment by syilphia** [comment]
i know how cobblegen from exu work, and i already said you can make it as early as day 3, now the problem is there is another one, that's use less resources but need iron plate, and can't be automated, this should be the first cobblegen option, but instead we got the exu one where it's already automated and while not cheaper, easier to get because it doesn't need to open up tech tree, darkosto said somewhere in this github that some mod is there for the sake of alternative, but in this case, nothing alternative about cobblegen, despite there are 2 way, the other is simply not worth it by the time you can make it

so either making PA cobblegen can be made with clay bucket, or make the ExU upgrade base created by IE plate on resonator instead of just gold pressure plate

**Comment by Darkosto** [comment]
Added a PA cobblegen recipe using clay buckets for 1.0.6
