### ISSUE TITLE
World creation

### ISSUE THREAD

**Issue by ExGeek1** [Darkosto/InvasionIssues#190]
Hello all,
I was trying to start a server for me and my friend, but when i started the server i got the vanilla world! Than i tried to copy the world for SP (in SP its an oky world) but i got same problems as i had with first world that server created(server in SP was set as bioms OP).
Pls share your answers on how to fix that.

**Comment by GenDeathrow** [comment]
OutDid you download the server files and read the read me file? It tells you what to do for that

**Comment by ExGeek1** [comment]
ik about that readme file but still doesnt work can someone post steps on how to do it

**Comment by GenDeathrow** [comment]
Google setting up a minecraft forge server.. make sure to change the world type to BOP that it tells you In the read me file.
