### ISSUE TITLE
HQM cannot complete a task.

### ISSUE THREAD

**Issue by MalContentFL** [Darkosto/InvasionIssues#191]
![2017-04-21_15 49 07](https://cloud.githubusercontent.com/assets/7505939/25293719/1b64330c-26aa-11e7-9a8d-664d4d70deff.png)

I apparently have 175% of the blocks needed. Now the quest won't complete and I cannot progress further.
It occured after updating to 1.0.5, presumably because when the quests were tweaked HQM doesn't recheck the amount of items.

**Comment by MalContentFL** [comment]
Anyone got a fix/know that its patched?

**Comment by Ommina** [comment]
A fix, if it is blocking your progression, is to use _/hqm edit_, mark it done, and move on.  I'm unaware if these kind of hiccups can be fixed via a patch or not.

**Comment by Darkosto** [comment]
Use HQM Edit to fix. This will only affect existing worlds and shouldn't affect new worlds.
