### ISSUE TITLE
map transfer to server

### ISSUE THREAD

**Issue by ExGeek1** [Darkosto/InvasionIssues#196]
i tried to start a server and i cant figure out how to do this step: Set your world type as "BIOMESOP" or the world will not generate properly.
i tried to generate it in singleplayer but when i transfer world it changes to normal server pls help a step by step answer will be the best 
thx all in advance

**Comment by GenDeathrow** [comment]
http://lmgtfy.com/?q=setting+up+your+minecraft+server+world+type
