### ISSUE TITLE
Ranged Pump not working

### ISSUE THREAD

**Issue by popemichael** [Darkosto/InvasionIssues#197]
Version 1.0.5 of Invasion.

For some reason ranged pumps are not working. It's saying that its scanning a block that has a liquid. However the tank attached is not filling up. This is because the the internal tank is not being filled with the liquid despite the ranged pump attempting to pump it (as viewed from the one probe).

To recreate (viewable via the one probe bauble):

1. Place down a ranged pump near the ocean. 

2. Power it however you like. 

3. Add a redstone signal using a lever

At this point you can see that its not filling the internal tank via one proble. You can try removing the water from the pump via tank or pipe, not trusting the bauble, but nothing will come out.

I've tried this on water and lava and it does the same thing.

I didn't have this issue before the last update, FYI.

**Comment by popemichael** [comment]
Suddenly as it started happening, it stopped happening.  Literally as I posted this.

I'm not sure why. This occurred through dozens of reboots last night as well as a fresh install.

**Comment by Darkosto** [comment]
Honestly, this has worked for me every time I've tested. Let me know if it happens again.

**Comment by popemichael** [comment]
I figured out the issue. My save decided to corrupt shortly after.

My arm started to switch sides from left to right over and over (one was a cyber arm, so I know it was a different arm). I tried to reboot Minecraft to help the issue. The save became corrupted and crashed Minecraft.

I loaded a backup from about an hour previous. After about an hour the same issue: the hands started appearing in different sides back and forth, then the save corrupted and crashed.

I have no clue what happened.

Let me know if you need the save or crash report. I got frustrated as I had a lot of time in. So I kinda gave up on things and stopped playing Invasion.
