### ISSUE TITLE
Default Config Change Request - Wither Tele

### ISSUE THREAD

**Issue by Zunth5** [Darkosto/InvasionIssues#199]
Progressive difficulty on the Wither is fine, and finding a creeper village for wither skel skulls seems appropriate for this pack, but the teleport ability makes killing the wither near impossible due to the lack of higher tier flight options (adv. Rocketry fuel doesn't last for a prolonged fight). I believe this would remain balanced so long as the blaze and wither skeleton spawning mechanic remains active.

**Comment by Darkosto** [comment]
Sure, I can remove this option. Thank you!
