### ISSUE TITLE
Infinity + Diamond Crossbow = Infinite Diamond Bolts

### ISSUE THREAD

**Issue by Lost-Ninja** [Darkosto/InvasionIssues#200]
Put infinity from a enchanted book on a heavy diamond crossbow, now when I fire the xbow I can pick up the fired bolts (diamond bolts).

**Comment by GenDeathrow** [comment]
It would be best to report that to the mod Author. From pack developer side all he can do is remove Infinity enchant.

**Comment by Darkosto** [comment]
Yes, I'm aware. This is not a bug.
