### ISSUE TITLE
Bugged server map or something ?

### ISSUE THREAD

**Issue by xFr3sHy** [Darkosto/InvasionIssues#201]
So me and my friend tried setting up a server for us two(lan based via hamachi), everything was working fine just the map was kinda bugged or is it normal on servers that when u break blocks they drop like vannilla minecraft(we didnt have to right click on them to pick them up after they were harvested) idk if thats normal or not ? We tried making a world in SP and copying it into the server files although the server properties were configured as they should be, but it still didnt work still the same problem with normal item dropping. If anyone had this problem or know how to fix it , help us plox :D

**Comment by beringtom** [comment]
that is not normal no... can you tell me what system you are hosting the server on? and post the startup file you are using?

**Comment by xFr3sHy** [comment]
Win7 64-bit, startup file is the default(.jar) that comes with the files u download

**Comment by beringtom** [comment]
the forge Jar I take it?

**Comment by xFr3sHy** [comment]
yes the forge.jar

**Comment by beringtom** [comment]
everything else is like normal right? have you tried redownloading the server zip?

**Comment by xFr3sHy** [comment]
hmm how do you mean redownloading, we downloaded the one from the client so there probably wont be anything different if i redownload it since the properties file is like it should be i guess i didnt change anything i just checked if the level-type is set to biomesop or hoe its called, but the otems are still dropping ?

**Comment by xFr3sHy** [comment]
items are still droping... *

**Comment by beringtom** [comment]
ahh so it's not a dedicated server, but a single player map you open up for lan?

**Comment by xFr3sHy** [comment]
amm not really, we downloaded the server zip from the client for the dedicated server, but it buggs the map somehow or a mod isnt working as it should , we even tried to make the map in SP and paste it into the server folder and its the same problem

**Comment by beringtom** [comment]
try and download this: https://minecraft.curseforge.com/projects/invasion/files/2408077

**Comment by xFr3sHy** [comment]
ye downloading from that link worked somehow :D ty for help
