### ISSUE TITLE
crash on world load

### ISSUE THREAD

**Issue by stded** [Darkosto/InvasionIssues#202]
Yesterday had a hardcore rush game till day 16. Had a lot of quests done. Made a party in a book at the game start, just to see what it is. Played solo. Today on load up world client crash. on the second try it loaded but all quest progression lost and world corrupted. base was full of sand piles blocks of cobble. and in near area lots of dirt and cobble changed to stonebricks slabs and marble fence.
a bit upset about it. 

Loading backups doesn't help.Making a new Invasion profile and coping save - also.

**Differences from other times i played this pack:**
 version 1.0.5(used to play 1.0.4)
made a party
enabled hardcore.

[crash-2017-04-24_23.19.30-server.txt](https://github.com/Darkosto/InvasionIssues/files/953048/crash-2017-04-24_23.19.30-server.txt)

**Comment by Darkosto** [comment]
Should be fixed  in 1.0.6

**Comment by ghost** [comment]
1.10.2 still same error log
