### ISSUE TITLE
[help needed] enchantments in this pack

### ISSUE THREAD

**Issue by ImelchorI** [Darkosto/InvasionIssues#203]
is there any way to get an overview of the enchantments in this pack and what they do?`

i dont know every single mod in this pack, and half the time just by the name i have no idea what kind of effect they have.

for example what is "berserking" for, or what does "spikes" or "scrapping" do? 

on a side note, im confused as to why i cant add enchantments to already enchanted items in the anvil. whatever im trying to do, i just get "too expensive" as a result.

i have a diamond crossbow only with power 3, and it straight up nopes me when i just put it in the anvil.

**Comment by Darkosto** [comment]
After testing: I just put added multiple enchants to a crossbow on 3 anvil operations, I can't reproduce the "too expensive" issue you're experiencing.

As for enchants in the pack, it's up to the player to learn about what the extra enchants are for. Experiential learning and self-discovery works well, or simply looking them up. I don't have the hours in the day to spend explaining what each item/mechanic in the entire pack does outside of the predefined questlines.
