### ISSUE TITLE
Dragon's breath

### ISSUE THREAD

**Issue by witdy002** [Darkosto/InvasionIssues#206]
Is there anyway to get Dragon's breath at all in the this mod, vendor's don't have the bank for me to trade nether stars or anything for them and there are no crafting recipes like in forever stranded  ??

thanks.

**Comment by ImelchorI** [comment]
doesnt a direct trade work? like putting a nether star into the inventory of a creeper and pulling the dragons breath out?

**Comment by witdy002** [comment]
direct trade? can't you only trade 1 item at a time to creepers, so I can't sell them nether stars as they don't have the bank to buy them

**Comment by Zunth5** [comment]
I can confirm that with each creeper villager vendor only having ~1000 voxels available, this is near impossible.

**Comment by Desim8r** [comment]
Kill witches.
