### ISSUE TITLE
Magnet Alternatives?

### ISSUE THREAD

**Issue by GliterShroom** [Darkosto/InvasionIssues#210]
In NEI/JEI you are easily able to see the Actually Additions, EnderIO, and Quantum Flux magnets, however only the EnderIO one works, and that's a 'mostly works' where it sucks items to you, but you still have to click them as they are rubberbanding around your head or turn off the magnet (I don't mind that magnet mechanic, just noting it).

My question is if there is a way to make the Actually Additions and Quantum Flux magnets work? Barring that, you may want to remove the recipes since otherwise you are wasting materials on something that has no explanation as to why it doesn't work (I know, interaction with the right-click to pick up vs vacuum inventory of vanilla).

**Comment by DemitriusM** [comment]
the Bagginses bags auto pickup blocks you break 75% of the time

**Comment by Darkosto** [comment]
Removed the AA and QF magnets, will be in the next update.
