### ISSUE TITLE
infinite voxels

### ISSUE THREAD

**Issue by ThatGravyBoat** [Darkosto/InvasionIssues#217]
you can buy ender chest that are for 0 voxels from the mayor in a voxel town and break them down to make 96 voxels from the 8 obsidian that you get. here is the link to the price of the ender chests http://imgur.com/Xd35XJr and heres the link to the obsidian sell price http://imgur.com/a/r98fc

**Comment by Darkosto** [comment]
Should be fixed up for the next update! Thanks!
