### ISSUE TITLE
Extra utilities builder wand Dupe Bug 

### ISSUE THREAD

**Issue by Stonethor1** [Darkosto/InvasionIssues#219]
dupe with the builders wand from extra util,  just have to have 2 items, place 1 and builders wand for ever

**Comment by Kashdeya** [comment]
This is a bug in EU2. Please report it to them.

**Comment by Stonethor1** [comment]
easy fix would be just to remove  just the EU2 wand

**Comment by Kashdeya** [comment]
We will not be removing it from the pack. The mod dev needs to fix it.
