### ISSUE TITLE
Server files 

### ISSUE THREAD

**Issue by Cybersnake71** [Darkosto/InvasionIssues#22]
There is no serverstart.bat how do I start my server in the server files?

**Comment by Cybersnake71** [comment]
like do I use the minecraft minecraft_server.1.10.2 file to start it or?

**Comment by Kashdeya** [comment]
if you want to run the server on your own computer there is millions of videos on youtube to teach you how. The server files that you downloaded are for server host.

**Comment by Cybersnake71** [comment]
ok thanks
