### ISSUE TITLE
No Luna - AR Gui

### ISSUE THREAD

**Issue by Zunth5** [Darkosto/InvasionIssues#224]
Looks like luna is not a thing so the last quest cannot be completed. We are playing in a server environment.

**Comment by Craken761** [comment]
Also encountered the above. No Luna selectable (only earth). Single player environment.

**Comment by Darkosto** [comment]
I've checked this multiple times, and it is definitely available. Have you moved the map around to find it? 

Just to clarify, every single time someone reports this I have checked and have had no issues locating it.

**Comment by Darkosto** [comment]
https://www.twitch.tv/videos/134062123?t=05h31m21s

**Comment by Zunth5** [comment]
Its not there, sorry. On the other block from AR that looks at the entire galaxy, it says earth 0 planets.

**Comment by Craken761** [comment]
Can confirm that it is not there for me.

https://youtu.be/yoQgFqXW5FM
(apologies for the colours, fraps doesn't get on with me it seems)

**Comment by GenDeathrow** [comment]
I would take this up with the mod dev of advance rocketry. He may have more insight ,than what we can provide. 

https://github.com/zmaster587/AdvancedRocketry/issues

**Comment by Craken761** [comment]
I managed to solve my problem.

Go into the advanced rocketry config, set reset from xml to true and launch the game.

Doing that meant that Luna popped up, and I had no problems travelling there.

**Comment by Zunth5** [comment]
Thanks for the help.

**Comment by Darkosto** [comment]
Fixed in 1.0.6
