### ISSUE TITLE
DUPE bugs, and stuff

### ISSUE THREAD

**Issue by Legatonin** [Darkosto/InvasionIssues#226]
Putting a fully repaired Diamond Chest Armor in Sag Mill turns to 14 Dimes, Boots is okay, Helmet is converts to 6, and Leggings Converts to 6 Dimes which is less than it's original amount.

Another Sag Mill Dupe:
Dimes or Emeralds will convert to 2x their dust form 50% per. If repeated process in smelting it again then Crushing and then smelting it again, then dupes it.

Edit:
Leather Leggings = 8 leather. Leather tunic = 10 leather, in Sag mill

**Comment by Darkosto** [comment]
Fixed in 1.0.6, thank you!
