### ISSUE TITLE
Spawning underwater?

### ISSUE THREAD

**Issue by stryker103** [Darkosto/InvasionIssues#229]
Dont know where to put this (new to github) but several times (about 3/5 spawns) ive been spawned 40-50 blocks underwater, often in the middle of an ocean
Of course, between piranhas and drowning i never make it far
As a result ive had to resort to enabling creative mode as soon as a spawn just to survive and find land
Dont know what can be done about this?

**Comment by GenDeathrow** [comment]
Nothing can really be done about this atm. It deals with the mods that add terrain generation.
