### ISSUE TITLE
[Suggestion] Finite water control mod

### ISSUE THREAD

**Issue by frenchiveruti** [Darkosto/InvasionIssues#232]
https://minecraft.curseforge.com/projects/finite-water-control  
https://www.reddit.com/r/feedthebeast/comments/68ay4p/i_found_the_perfect_finite_water_mod_but_it_only/
Is it a good idea? I believe it will give a better playability to the modpack.

**Comment by Darkosto** [comment]
The pack already has finite water

**Comment by frenchiveruti** [comment]
Hi Darkosto, Indeed I already knew that we have finite water, but what this mod does, is to transform the water sources depending on where they are placed, so spaces like oceans or rivers are infinite water sources, but lakes or marshes are not.
This way, a player could choose to live by an ocean (at a piranha risk) and be able to use the infinite water from it, but not be able to create a 2x2 infinite water source for free.
The reddit link I gave goes a little better on the arguments, but I just posted it here as a suggestion.
Cheers!

**Comment by TheSaucyWelshman** [comment]
`    B:"Prevent infinite water source blocks outside biomes with the WET type"=true
`
This is already the case via WTF's Expedition: Gameplay.

**Comment by frenchiveruti** [comment]
Hi Billy, if that's the case then my suggestion should be closed, I've not seen this behavior when I set a base right next to an ocean, maybe the water blocks on the shore where on a non WET biome, so that was my problem.
Thanks.

**Comment by Darkosto** [comment]
Honestly, after reviewing the finite water control mod tonight for quite a while, it's not going to work for the pack. The last of selecting Deep Oceans as an infinite source the trouble I had with it isn't worth the effort. Thank you for the suggestion though!

**Comment by frenchiveruti** [comment]
Great, I understand, thanks to you for the modpack, having lots of "[fun](http://dwarffortresswiki.org/index.php/v0.34:Losing)" with it
