### ISSUE TITLE
WAILA (via The One Probe) not working

### ISSUE THREAD

**Issue by weedenbc** [Darkosto/InvasionIssues#234]
Started a new game of Invasion a couple days ago (installed via the Curse launcher). 

I cannot get the WAILA-type display from The One Probe to work. I have crafted both the probe, and tried wearing the goggles from the quest. The first time I used the probe, I got an overlay pop-up asking to configure the position of the window. But there's no window. Tried the standard NUMPAD key commands to enable it, but nothing. 

Also tried going into The One Probe cfg files and setting the required flag to "0", still nothing.

**Comment by Darkosto** [comment]
Can't reproduce.
