### ISSUE TITLE
Crafting Fries from Pam's consumes kitchen knife

### ISSUE THREAD

**Issue by felixkraas** [Darkosto/InvasionIssues#237]
When crafting Fries from Pam's Harvestcraft only the Bakeware is returned to the player and the Kitchen Knife is consumed. I would suggest that the crafting damages the tool instead of eating it, the current state makes it impossible to craft even smaller quantities of fries. Especially early on.

**Comment by Darkosto** [comment]
Fixed in 1.0.6, thank you!
