### ISSUE TITLE
Plans for Bugfix update? 

### ISSUE THREAD

**Issue by ChetwyndKid** [Darkosto/InvasionIssues#238]
Hey, 
After finding a few bugs (Which have already been listed) A few of them have been fixed via Mod Author.
Is there a date when we should expect an update with the updated mods?

Thanks.

**Comment by Darkosto** [comment]
There is no date to expect any update. I'm currently in the middle of a bugfix update and just got over being sick for the last 4 days. The update should come out when it's ready.
