### ISSUE TITLE
Builders wands and placing Tiered Walls. [issue/bug]

### ISSUE THREAD

**Issue by bbqx** [Darkosto/InvasionIssues#239]
That may only effect server play? I'm not sure one how open passive modular defense is coded, but when placing walls using the wand you cannot remove the placed wall. You instead get an error message that says "you do not own this". 
My guess is that the wand places the blocks as a fake player?

Not sure what mod-dev to message on that one, BUT better builder wands does had a block _**black list**_ option in is settings. I don't know if settings files carry to client side but assuming they due can you add walls and fences to the list? (Anything that you have to shift click to break really)

Too late for me, but will save other players for encountering my issue. Also I did not test the ExtraU2 builder wand. It my have the same issue. If it does maybe remove/disable from the pack?

**Comment by Darkosto** [comment]
Fixed in 1.0.6
