### ISSUE TITLE
Armour recyling is a positive feedback loop

### ISSUE THREAD

**Issue by Turmfalke2** [Darkosto/InvasionIssues#240]
hi,
A Golden Chestplate can be recycled using a wirecutter into 20 gold ore pieces. 20 gold ore pieces can be crafted into 5 Gold chunks which can be macerated into 10 gold dusts. Once smelted 8 out of the 10 gold ingots can be used to craft a new chestplate. 
This leaves us at 2 gold ingots per point of durability on the wirecutter. A wirecutter cots 2 sticks and 1 ingot (above also works with iron armour).

**Comment by Darkosto** [comment]
Yep, this has been reported multiple times and has been reduced many times. The problem here is: If the values are turned down, players report not having enough materials to work with. Or, if they are used for scrapping then players report you get too many.

**Comment by Darkosto** [comment]
Fixed in 1.0.6
