### ISSUE TITLE
[Request] player heads list

### ISSUE THREAD

**Issue by vaptsiukas** [Darkosto/InvasionIssues#241]
Hi Darkosto,
I'm about to finish all quests and looking forward how to extend world with an additional "purpose". I would like to collect all the different player heads (aka get 'em all poke-heads)

I've read somewhere that all raiders are real players witch are patrons or smth. Is there a way to get these in- game players names list to be published?

And thanks for a great modpack!

**Comment by Darkosto** [comment]
This is actually a revolving list that is dependent on my twitch subscriber list. Basically, I could get a list out, but it could change in the same day if someone unsubs or if new subs are added.

Having said that, you can see the current list in a config file: Configs/raiders/raider.json
That list will give you the most up-to-date list of who is currently loaded into your game :)
