### ISSUE TITLE
The server for Invasion 1.10.2-1.0.5 does not start with any mods loaded.

### ISSUE THREAD

**Issue by ghost** [Darkosto/InvasionIssues#245]
When I accept the eula and start the server it loads a default minecraft server. I have tried renaming the "llibrary" folder to "library" and that did not seem to help.

**Comment by Darkosto** [comment]
This is typically what will happen when you don't set the server up and run Forge. You're running it as a vanilla server. I provide the files, it's your job to finish the setup for your own personal purposes.
