### ISSUE TITLE
Bread, Bread, Bread

### ISSUE THREAD

**Issue by Arkeus121** [Darkosto/InvasionIssues#251]
When crafting bread I noticed there are two recipies:
1. Crafting flour and then using water, salt and a mixing bowl to make dough, following this you use the furnace (any type) and you have bread.

2. An alternate recipe shows that by using the enderio sag mill, you can turn wheat into an alternate flour and just smelt this in an actually additions furnace (Specific).

I think this is an issue as both flour types can be crafted into bread using the first method. I have realised that to craft it using method '2' you do need more advanced machines, so I'm not sure if this is an issue.

**Comment by Darkosto** [comment]
Right, and method two doesn't actually lead you to bread since all you can do is make it into flour.

**Comment by Arkeus121** [comment]
![image](https://cloud.githubusercontent.com/assets/9905886/25783045/531e2fb4-334d-11e7-9efe-69f5177b0072.png)

![image](https://cloud.githubusercontent.com/assets/9905886/25783050/605b87bc-334d-11e7-83e6-358b0d08ddd8.png)

**Comment by Arkeus121** [comment]
![image](https://cloud.githubusercontent.com/assets/9905886/25783057/938fd462-334d-11e7-875d-e7af7f598220.png)

![image](https://cloud.githubusercontent.com/assets/9905886/25783059/a1225e2e-334d-11e7-8918-9e26f27f4fc0.png)
 
...This makes bread
