### ISSUE TITLE
Huge lagg spike

### ISSUE THREAD

**Issue by ghost** [Darkosto/InvasionIssues#252]
When I look in my inventory I see my arms going crazy also the mobs their arms are going crazy. After that there are huge visual bugs and I move very fast to somewhere then I can't move and I need to relog.
![Uploading 2017-05-07_15.11.42.png…]()

**Comment by ghost** [comment]
Oh yeah this is in HQM and it all started after all the marble blocks got replaced by marble stairs so I relogged then my whole quest book got reset and then the thing above started and now I can't play because after 3 min I get those glitches and need to reload.

**Comment by GenDeathrow** [comment]
Betterfps: https://github.com/Darkosto/InvasionIssues/issues/92

**Comment by GenDeathrow** [comment]
And this https://github.com/Darkosto/InvasionIssues/issues?q=is%3Aissue+is%3Aopen+label%3AHQM
