### ISSUE TITLE
Raider setting block on fire generates a massive RAM leak because of the size the log gets.

### ISSUE THREAD

**Issue by frenchiveruti** [Darkosto/InvasionIssues#256]
This issue is reported here on GenDeathrow/PlayerRaiders#4 where the log becomes a massive file of ~140MB and just spams the log.  
Can we get a quick fix update? 
Or we have to wait for 1.0.6

**Comment by GenDeathrow** [comment]
This will already be fixed in version 1.0.6 of invasion. 
https://minecraft.curseforge.com/projects/raiders/files/2413494

**Comment by frenchiveruti** [comment]
Ok!
For anyone who stumbles onto this before 1.0.6 , just download the latest version of Raiders mod and replace the one in the mod folder with the latest one, it doesn't give any errors.
Cheers!
