### ISSUE TITLE
Advanced Gens

### ISSUE THREAD

**Issue by witdy002** [Darkosto/InvasionIssues#260]
SynGas was producing 5mb before last patch but now only produces 0.2mb is this intended?

also can't build new ones as iron tubing recipe now makes spear hook's instead

edit:  just saw issue 129, the gens worked fine using the default config,  as with current config max output would be 2mb as that would be max modules installed

**Comment by Darkosto** [comment]
Fixed in 1.0.7, removed the testing file I was using in dev.
