### ISSUE TITLE
Unable to Craft Most AIOT's

### ISSUE THREAD

**Issue by Badger-One** [Darkosto/InvasionIssues#27]
So the recipe for an AIOT includes both an axe and a sword obviously. I don't know what mod puts the leveling system on swords and axes by default but you can't craft with them as vanilla tools. You can clear the NBT by putting either the sword or axe through the crafting grid then crafting with it before it touched your inventory but having both an axe and a sword in the same recipe, it's just not possible.

**Comment by Darkosto** [comment]
I'll take a look and see if I can make this work for 1.0.1. Thank you!

**Comment by Darkosto** [comment]
Fixed in 1.0.1
