### ISSUE TITLE
Server stuck on boot up

### ISSUE THREAD

**Issue by Nvmbishop** [Darkosto/InvasionIssues#273]
First time trying to play the server so i might be doing something wrong. However when I try to boot up the server It gets stuck on Ender IO.

![image](https://cloud.githubusercontent.com/assets/28612245/25926355/bf84f7e8-35bc-11e7-87f3-fddcabf4ec3b.png)

I have tried to do multiple clean installs on the server. Anything I might be doing wrong is there something happening?

**Comment by beringtom** [comment]
can we get the full log please :)

**Comment by Nvmbishop** [comment]
Yeah here is the log, I tried to launch again to show the most recent one. I couldn't directly upload the text document so I zipped it up. If there is another way you want me to put it in please tell me. Im a bit a new to using GitHub.
[fml-server-3.zip](https://github.com/Darkosto/InvasionIssues/files/991563/fml-server-3.zip)

**Comment by beringtom** [comment]
pastebin.com and a link would be fine, really don't wanna open a zip :)

**Comment by Nvmbishop** [comment]
Yeah it tell me when I try to paste it that it reaches the max, should I do it in multiple links?

**Comment by Nvmbishop** [comment]
https://pastebin.com/5CCnhPVm

That is towards the end of the log, If you want more is there a way to paste the whole log or something? without hitting the cap for free users.

**Comment by beringtom** [comment]
so looking at your log it just seems that the server stalls, do you use any startup script?
does it also happen with the server files from 1.0.6?

**Comment by Nvmbishop** [comment]
No Script that I'm aware of, I can try 1.0.6. I will tell you how that goes.

**Comment by beringtom** [comment]
I suggest a startup script for windows, makes things easyer ;)

**Comment by Nvmbishop** [comment]
I have the same issue with a server on 1.0.6 as well. Pretty much the exact same thing.

https://pastebin.com/yFGQ9xVq

That is the log for the 1.0.6 I think it would be the same thing. Maybe it is my system or something?

**Comment by beringtom** [comment]
https://pastebin.com/719LcdtM

This is our start script, rename the forge.jar file to server.jar and change the 5500 to what ever you want for max ram (in Mb) save it as a .bat file in your server folder and run it from that

**Comment by Nvmbishop** [comment]
I tried to run it but it keep instantly closing windows, I'm not sure why it isn't doing anything..

![image](https://cloud.githubusercontent.com/assets/28612245/25928005/b3ba3152-35c7-11e7-832c-77337c7561a4.png)

Was that the correct change? was it properly done? Sorry for the hassle. Thanks again for helping me

**Comment by beringtom** [comment]
just edit the file and on a new line write "pause" no qoutes

**Comment by Nvmbishop** [comment]
yeah i got a cmd screen now.
![image](https://cloud.githubusercontent.com/assets/28612245/25928131/6eb69b4e-35c8-11e7-9ef2-0e1058d4c2d1.png)

Is there something wrong?

**Comment by beringtom** [comment]
nothing I can see, remove the "nogui" at the end and see if you get a window

**Comment by Nvmbishop** [comment]
No change they still instantly drop

**Comment by beringtom** [comment]
lower 4500 to 3000 just to check

**Comment by Nvmbishop** [comment]
Nope I tried 3000, than 2000. I have 16gb total and currently only using 30% of it. if you think it is a ram issue

**Comment by beringtom** [comment]
okay try running it as Administrator, last thing I can come up with, can you link where you got the server files from?

**Comment by Nvmbishop** [comment]
No dice even as admin, the server download is from https://minecraft.curseforge.com/projects/invasion

**Comment by beringtom** [comment]
can you zip your files and let me try to run it, hopefully I get the same error :p

**Comment by Nvmbishop** [comment]
Is there a platform you prefer me to upload it. It is to large for github

**Comment by beringtom** [comment]
nope, just pick one

**Comment by Nvmbishop** [comment]
https://www.dropbox.com/s/wyruwg7brkecgz0/Invasion%201.0.7%20Server.zip?dl=0

Also I feel bad for spamming so many messages on the board, is there like a help discord I could use or something?

**Comment by beringtom** [comment]
okay, so I found the error, you renamed the jar file "server.jar" so t's actually called server.jar.jar renamed it to "server" only  and you should be good ;D

**Comment by Nvmbishop** [comment]
Nope, still doing the same thing. Was it working for you when you changed it?

**Comment by beringtom** [comment]
yeah, worked for me, started up instantly

**Comment by Nvmbishop** [comment]
Man this is annoying I don't know why mine is still doing it.
![image](https://cloud.githubusercontent.com/assets/28612245/25928979/423dde56-35cd-11e7-9bf2-22261c0690ba.png)
That looks right to me

**Comment by beringtom** [comment]
looks just fine, I can't tell you what's wrong, sry :(

**Comment by Nvmbishop** [comment]
Is there someone else that could potentially help me? Like do you think it is a system conflict or something? This is my first time having an issue with a server and I was looking forward to playing this pack.

**Comment by frenchiveruti** [comment]
Do you have updated Java 8 u131?

**Comment by Nvmbishop** [comment]
im on 121 right now, I can update right now and see if that helps.

**Comment by Nvmbishop** [comment]
That actually fixed it, I didn't think that was issue. Thanks for the help. I'm also going to close the thread now cause my issue is solved. Thanks again for helping me!

**Comment by frenchiveruti** [comment]
Haha, the ol' update solution, enjoy your survival. 😀
