### ISSUE TITLE
My hand is on the left side.

### ISSUE THREAD

**Issue by Enderboy360** [Darkosto/InvasionIssues#274]
After doing somethings with Cyberware my hand moved to the left side. I knew what caused this, the right cyber arm. BUT after I removed the cyber arm wanting my right arm back, it stayed on the left side. Later I made a new world to test some thing and my hand was still on the left side.

Also if I try to change my main hand in Skin customization in the options it flips to the right for half a second than back to the left hand

**Comment by frenchiveruti** [comment]
Here's the mod gitpage:
https://github.com/Flaxbeard/Cyberware/issues
