### ISSUE TITLE
No Luna destination in 1.0.7 version

### ISSUE THREAD

**Issue by Yeokrast** [Darkosto/InvasionIssues#278]
I saw where you said this was fixed in 1.0.6 of Invasion, but I'm now on 1.0.7.  I see Earth very clearly and can even select it, however, I've moved all around the "space map" and couldn't find Luna.  I can attach screenshots, if you'd like.

**Comment by frenchiveruti** [comment]
You should attach screens 😄

**Comment by Yeokrast** [comment]
![image](https://cloud.githubusercontent.com/assets/28624437/25976902/c94d2754-3685-11e7-9204-1191a69e1831.png)
![image](https://cloud.githubusercontent.com/assets/28624437/25976918/dd56d8ee-3685-11e7-807a-1395cda5f878.png)

**Comment by GrandPhoenix** [comment]
Hey Yeocrast. I had the same problem as you, but I found a fix.
Try to delete the \Invasion\saves\<savegame folder>\advRocketry\temp.dat file. and load the world again.

**Comment by Yeokrast** [comment]
I can confirm that this worked for me.  I wonder if it's because of upgrading from version to version.

Good to close ticket!

**Comment by frenchiveruti** [comment]
You can close it yourself! :+1:

**Comment by ghost** [comment]
Confirmed again.  I also was an upgrade from 1.0.6 to 1.0.7.
