### ISSUE TITLE
Recipe Conflict (iron wand with iron lance)

### ISSUE THREAD

**Issue by CorGaming** [Darkosto/InvasionIssues#279]
The title says it all, 2 itens, same recipe, but I can only create the lance. 

Thx and keep the pack going :).

**Comment by frenchiveruti** [comment]
I came here to report the exact same thing.
The Iron Lance from Kaishi's and the Iron Builders Wand from Better Builder's wands share the same recipe.  
Also, happy Bday @Darkosto ! (I know it was yesterday)

**Comment by CorGaming** [comment]
This block the quest line of minecolonies because we cant craft the wand required...it conflicts with stone lance or something like that. Unless I was drunk or I made the quest before that conflict xD.

**Comment by frenchiveruti** [comment]
It's a craft or a detection quest?

**Comment by witdy002** [comment]
the 3 betters builders wands stone,iron and diamond all have recipe conflicts with lances

**Comment by Darkosto** [comment]
Should be fixed in 1.0.8.

To CorGaming, what tool are you referring to that can't be made to finish your quest? Do you mean the "Building Tool"? That recipe was changed long ago and does not conflict with anything.

**Comment by frenchiveruti** [comment]
@Darkosto There's a quest that orders us to create a building wand made of iron, and as the recipe conflicts with the lance you can't finish it, so that's the quest @CorGaming refers to.
