### ISSUE TITLE
Minecolonies and torch 

### ISSUE THREAD

**Issue by Waisse** [Darkosto/InvasionIssues#28]
How I am supposed to make my colony if buildings catch on fire with torches nearby ? Torches are part of most buildings, fix please.

**Comment by Kashdeya** [comment]
torches placed during world/chunck load will not catch things on fire and torches placed by NPC's should not catch things on fire.

**Comment by Darkosto** [comment]
I just tested this and the torches placed by the minecolony builders don't start anything on fire.
