### ISSUE TITLE
Coke Oven not functioning in SP

### ISSUE THREAD

**Issue by torres303** [Darkosto/InvasionIssues#280]
I just found out when i launched my game this afternoon and after testing it in creative i can confirm that the coke oven from IE isn't making the creosote oil. I've tried wood and  coal/charcoal the smelting meter will be at max when you put the items in, but that's about it. It doesn't make the creosote oil. Since making the oil is a quest i don't think anyone will be able to progress w/o it.

~Torres

Btw. where's my piece of birthday cake I'm owed. Kappa

**Comment by ghost** [comment]
It worked for me?

**Comment by Darkosto** [comment]
Yeah, tested myself in the latest version and it was working as intended. Try breaking and replacing?
