### ISSUE TITLE
Clay to Lapis Recipe

### ISSUE THREAD

**Issue by Degenerecy** [Darkosto/InvasionIssues#284]
In the NEI it shows the Atomic Reconstructor can change Clay to Lapis but instead turns Clay directly into Palis Crystal.  It would be easy to get Lapis this way so I am guessing this is intentional.  Not a big thing but a small change to the NEI recipe list would make it more clear.   Also searched for this topic, and could not find any.

**Comment by Yeokrast** [comment]
I've had the same experience and my workaround is to make sure the clay is at least 2 blocks away from the Atomic Reconstructor.  I haven't had an issue since.  The clay is supposed to go to Lapis.

**Comment by Darkosto** [comment]
The recipe shows correctly, the reconstructor is turning the lapis into palis. I've had no problems myself making clay into Lapis multiple times during testing.

**Comment by Degenerecy** [comment]
Tested, forgot to reply, it seems when Clay is too close to the Reconstructor it will turn it into Palis.  Must be 3 blocks away or further.
