### ISSUE TITLE
Minecolonies : crafting table ?

### ISSUE THREAD

**Issue by Waisse** [Darkosto/InvasionIssues#29]
My builder's hut lvl 2 require a crafting table, how do I get that ? It doesn't work with rickety/sturdy/reinforced crafting table ...

**Comment by Darkosto** [comment]
I'll get this fixed up today for the update coming out. Thanks!

**Comment by Darkosto** [comment]
Making this change is beyond me. I've tried changing the schematics to allow for our own Crafting Tables but it isn't working correctly. I'll just write a quest to allow the player a vanilla crafting table for this specific purpose. It's not idea, but it should take care of the problem.

Issue reference:
https://github.com/Minecolonies/minecolonies/issues/747
