### ISSUE TITLE
Using VeinMiner Ability when collecting trees is redundant.

### ISSUE THREAD

**Issue by Xcrysdale** [Darkosto/InvasionIssues#293]
I had been collecting wood from trees and whenever I used the VeinMining ability to destroy the whole trunk all the logs are destroyed by the leaf block at the top falling on them. This makes collecting wood a take quite a bit longer and be a bit more infuriating. Don't know if there is even possibly a fix for this, seeing as the leaf block is a totally separate block type.

Thanks for reading, Xcrysdale.

**Comment by GenDeathrow** [comment]
TBH not much could be done about this atm. I have seen a lot of ppl use this with little to no problem. Also it's Ore Excavator.

**Comment by liorrozen** [comment]
@Xcrysdale - My technique it to get rid of the leaves *before* getting at the wood. This way your wood entities don't disappear **and** there is no risk of leaves falling on your head causing damage.
