### ISSUE TITLE
Cannot equip ring of regen in bauble slot

### ISSUE THREAD

**Issue by weedenbc** [Darkosto/InvasionIssues#296]
Made a ring of regen, but cannot equip it in either of the two baubles slots designated for rings. I can only equip it in the shield (off-hand slot), where it doesn't have any effect.

**Comment by ghost** [comment]
You need to hold the ring in your hand to take effect you can't wear it.
https://ftbwiki.org/Ring_of_Regeneration

**Comment by weedenbc** [comment]
Well ok then. Did not know that!
