### ISSUE TITLE
Staff of Travelling doesn't get charged by AA-Battery (Tesla-API missing)

### ISSUE THREAD

**Issue by BuggaNoia** [Darkosto/InvasionIssues#298]
To let EnderIO-device accept wireless/in-inventory RF it needs the Tesla-API. Therefore the mod Tesla-1.10.2-1.2.1.50.jar (or later) needs to be added.

See: https://github.com/SleepyTrousers/EnderIO/issues/3992 , MatthiasMann commented on 14 Jan

**Comment by Degenerecy** [comment]
Same with the Armor stuff, only thing that I seen the battery charge is the scanner.

**Comment by frenchiveruti** [comment]
This should probably be reported to both the EnderIO and (I think extrautilities? actually Additions?) mod developers.
It's not a modpack issue.

**Comment by ghost** [comment]
You could add the mod yourself...

**Comment by BuggaNoia** [comment]
@HILeotomasMC : Yeah I already did so. Posted this issue to give others the opportunity to do it the same way.

@frenchiveruti: I don't think so. As the EnderIO team stated in the linked EnderIO issue there is no bug on their side. Instead they say that anybody, who like to use their mod, has to add the TeslaAPI "mod" also.
And btw: This solve the issue perfectly, so I guess the EnderIO guys are right.

**Comment by frenchiveruti** [comment]
@BuggaNoia YEah sorry didn't saw the referenced issue. I always thought that Tesla energy was part of Forge by default.

**Comment by Darkosto** [comment]
This is simply due to not every mod working with each other in terms of power. This is something that happens a lot and you'll notice gets worse in 1.11. I have no intention of adding Tesla, honestly. This is something that will have to be done within the confines of the pack and using the mods to charge their own items.

**Comment by frenchiveruti** [comment]
Damn be power APIs! We need a general API to stop this nonsense!
https://xkcd.com/927/
