### ISSUE TITLE
Save  bug

### ISSUE THREAD

**Issue by XxpouglouisxX** [Darkosto/InvasionIssues#30]
So i saved a world and when i got back some blocks switched whit nearby blocks

**Comment by XxpouglouisxX** [comment]
like this:
![2017-03-28_14 59 24](https://cloud.githubusercontent.com/assets/26741490/24406055/4654d530-13c7-11e7-972d-ec453ac2a315.png)

**Comment by Darkosto** [comment]
Sent a message to the dev of the WTF Expedition mod for this fix.

https://github.com/WhiskyTangoFawks/Expedition/issues/127

**Comment by XxpouglouisxX** [comment]
thx for sending/making that issue on mod

**Comment by Darkosto** [comment]
Fixed in 1.0.4
