### ISSUE TITLE
Crafting Tables for Minecolonies

### ISSUE THREAD

**Issue by Mikhaila666** [Darkosto/InvasionIssues#304]
I just started a colony, have only done builders hut, level 1 townhall, upgrading to level 2. 

Builder is asking 14 crafting tables. I can get these by crafting 112 rickety crafting tables into 14 crafting tables, but that is one hell of a lot of exploration. And who knows what he will need next. Just this little bit of building has taken stacks of logs, stairs, slabs. Can we please have an easier recipe for the regular crafting table for recipes and minecolonies? Minecolonies is a huge amount of materials already.

**Comment by frenchiveruti** [comment]
I believe minecolonies is just useless for the modpack.
Raiders, even friendly ones, will attack you colonists, and the colonist aren't that useful to be honest.

**Comment by Mikhaila666** [comment]
I see it as a nice challenge to do late game. It's taking a huge amount of resources that's for sure. I was building a huge platform a bit in the air with a large number of laser turrets to discourage mobs cobbling up. Getting a few hundred oak stairs, fences, logs, dirt mean't a lot of running around and tearing down buildings with excavator and stacks of good food. But hitting that demand for crafting tables just stopped me. I could get past it, but hell, that's for just the first upgrade to the townhall. There's a lot left to build. 




-----Original Message-----

**Comment by frenchiveruti** [comment]
Well... You could always cheat that, I mean, those are balance issues that need to be solved on a modpack that relies a lot on mod configs that are meant for a vainilla esque scheme, so when for example MineColonies hit a requirement that should be extremely easy on normal gameplay (as for the crafting tables or furnaces, or even birch wood!) it turns into a pain and cry out to be done on in a way that renders the entire mod useless, as its core feature gets crippled.

**Comment by Mikhaila666** [comment]
In single player, yes, you can just cheat them in. But doesn't work on a server. I don't know how normal crafting tables work in invasion, if they work or not. Was hoping that if they were disabled there could just be an easier recipe to do minecolonies with. Furnaces aren't hard, birch wood I have tons of from buildings and trees are in the wild. But getting 126 crafting tables is another thing entirely. Just skipping minecolonies at this point. Problem solved.




-----Original Message-----

**Comment by frenchiveruti** [comment]
Huh... My stupid map is just endless steppes, deserts and tundras, so I don't have any birch trees.
The normal crafting tables aren't placeable so they won't work like they normally do.

**Comment by Mikhaila666** [comment]
I find little patches of greener biomes, and some houses will have birch trees around them. 


If the normal tables can't be placed, just making a simpler recipe like rickety plus a cobblestone would be much better. Still only usable for Minecolony or recipes, but not so harsh for mine colony. 


hmmm, does the builder in MColonies actually place the tables he asks for? or do they become rickety ones?




-----Original Message-----

**Comment by frenchiveruti** [comment]
I really really don't know as I never got into MineColonies and I've never used a creative world for the modpack-

**Comment by Darkosto** [comment]
"Can we have an easier recipe for crafting tables?" - Sorry, no. If the resources are outside of what you feel is necessary then you don't need to complete that mod. It's not something I'm interested in looking further into. Thanks for the report.
