### ISSUE TITLE
Item with no crafting recipe.

### ISSUE THREAD

**Issue by frenchiveruti** [Darkosto/InvasionIssues#308]
Raiders drop a circuit board that can't be used in any recipe, making it useless and cluttering the loot tables of the game.

**Comment by ghost** [comment]
Some items dont have support for JEI recipies. What mod it the item from? If that mod has its own crafting block, it might not show that in JEI. Also, your title suggests that there is something you want to make, but cant.

**Comment by Darkosto** [comment]
# If false Raiders dont drop samples. THIS IS THE ONLY WAY TO GET THEM [default: true]
    B:"Drop Tramsmitter Part"=false

@GenDeathrow This is disabled in the config but are still dropping?

**Comment by frenchiveruti** [comment]
@HILeotomasMC Hi there, I think those are just a mistake for real, the transmitter part that one can use is obtainable via the use of a wirecutter and any transmitter, those are dropped by raiders and don't seem to have any purpose nor OreDictionary reference.

**Comment by GenDeathrow** [comment]
@frenchiveruti have your configs been changed? I just tested this in my dev environment with a 100% drop rate, when the setting is true they drop all the time.. when its false they don't drop.

**Comment by GenDeathrow** [comment]
@Darkosto I just checked the version on curse, its the same as my dev enviroment still.

**Comment by frenchiveruti** [comment]
@GenDeathrow Then it must be a mistake on my end... huh...
To be honest I thought it was a default thing because those drops were new as they stopped dropping limbs, so I really thought those replaced the limbs for something.
I'll disable them then 👍

**Comment by GenDeathrow** [comment]
It's sounds like config got messed up cause the limbs are suppose to be set up in raiders config as well. Try reinstalling?

**Comment by frenchiveruti** [comment]
Sure thing, I'll reset the configs as they seem to be the issue here.

**Comment by LAWolves** [comment]
they're not dropping limbs for me either, but no transmitter problems.

**Comment by GenDeathrow** [comment]
@LAWolves they aren't suppose to be dropping transmitters in invasion. They are suppose to be dropping limbs though, Means your configs got messed up in download.

**Comment by Darkosto** [comment]
Fixed in 1.0.8, limbs had their ID's changed.
