### ISSUE TITLE
EnderIO normal filters are harder to make than advanced ones

### ISSUE THREAD

**Issue by frenchiveruti** [Darkosto/InvasionIssues#309]
The fact that the filter uses a hopper renders the recipe very mid game, I know that in the moment you can make those you should already have a presser for the tin plates, but that extra step to create a rather simple item needs a balance.
My suggestion is an iron chest or something similar.

**Comment by ghost** [comment]
You don't mention how normal filters are harder to make. Could you explain what you mean? That way Darkosto will know what you mean.

**Comment by Darkosto** [comment]
I don't agree that it needs a balance. I also do not agree that it's harder to make than the advanced variant. We'll have to agree to disagree on this particular issue. Thank you for the report!

**Comment by frenchiveruti** [comment]
Ok! No problem :)
