### ISSUE TITLE
HQM data.json file size - Server connection issue

### ISSUE THREAD

**Issue by Yorkforce** [Darkosto/InvasionIssues#31]
Unfortunately when the hqm data.json file size reaches around 1,000,000 bytes no one is able to log into the server anymore.
https://pastebin.com/Ea3MFc0i

I believe this is intentional coding from the hqm dev, the issue existed in 1.7.10 also, which was flatly denied until we had a java programmer prove the issue, at which point the mod dev stated that hqm wasn't for large servers.

Currently the server has been online for 3 days and has had 23 players join, at which point the world/hqm folder needs to be deleted to allow players to join again.

*cough* I don't believe BetterQuesting has this issue *cough* :nerd_face:

**Comment by Darkosto** [comment]
BQ may not have this issue, and honestly you're speaking to the person who was a co-creator of Better Questing who chooses not to use the mod. I'm not a fan of much how Better Questing works, I'll save you time on my many reasons for that.

Having said that, I will discuss this with one of the current maintainers of the mod and see what I can do. If I can get it to work then we'll all be in better shape.

**Comment by Yorkforce** [comment]
Thanks Darkosto, I had noticed the config folder for betterquesting in the server files which is why I mentioned it, I guessed you had either planned to use it and changed your mind or were planning on switching, but that would be great for anything you could do, hqm just doesn't like SMP unfortunately :(

**Comment by Darkosto** [comment]
Good news! I just got a testing build from HQM that should fix this issue right up!! Should be available in the next pack update coming out soon :D

**Comment by Yorkforce** [comment]
File size has now passed the previous limit and server is looking good, so can confirm its fixed :+1:
