### ISSUE TITLE
Mob Masher (Mob Grinding Utils) Not Craftable.

### ISSUE THREAD

**Issue by Lost-Ninja** [Darkosto/InvasionIssues#315]
Running 1.0.7, just tried to craft this block, a recipe is listed in JEI/NEI but it has no result when you place the items in a crafting bench

**Comment by DemitriusM** [comment]
Its the iron swords, try placing them in your 2x2 crafting grid to change the stats on it. I was able to craft it after several tries.

**Comment by Lost-Ninja** [comment]
Ah that makes sense thanks... :)

On 29/05/2017 13:22:48, "DemitriusM" <notifications@github.com<mailto:notifications@github.com>> wrote:


Its the iron swords, try placing them in your 2x2 crafting grid to change the stats on it. I was able to craft it after several tries.

**Comment by Darkosto** [comment]
I just went ahead and changed the recipe to accept the Dungeon Tactics swords to start off so there's less confusion.

Thanks for the report, will be out for 1.0.8
