### ISSUE TITLE
Pausing Server progression when In-game

### ISSUE THREAD

**Issue by LAWolves** [Darkosto/InvasionIssues#317]
How to do so? Like to edit the Spawn in creative mode or so.

**Comment by st753m** [comment]
Have you tried "/gamerule doDaylightCycle false"?  I can only confirm that it works in singleplayer.

**Comment by LAWolves** [comment]
Will try and report whether it's working, thanks.

**Comment by Darkosto** [comment]
Log off the server to pause progression.

**Comment by LAWolves** [comment]
I meant I wanted to stop the progression so I could edit the map BEFORE having my friends connect, without advancing the time and consuming the first day of peace.
