### ISSUE TITLE
How to start for a newb

### ISSUE THREAD

**Issue by tweed0123** [Darkosto/InvasionIssues#318]
I downloaded the file, extracted it, changed EULA to true, and ran forge-1.10.2...etc-universal and after a bunch of errors and stuff, it finally just stops.  Some errors like, missing translation config.capacitor.etc (multiples), config files out of dates, 

I feel I am missing something huge/easy.  Is there something else I am supposed to do?  There isn't much in the readme.  I'm totally new to MC and modding.

**Comment by st753m** [comment]
Have you tried using the Twitch / Curse launcher?

**Comment by tweed0123** [comment]
You can do that to start a server?

**Comment by st753m** [comment]
Oh, you're trying to make a server?  No idea, sorry; I've only played singleplayer or joined other's servers.

**Comment by Cyric313** [comment]
best thing is to make a start script in a bat file if you are running windows... 
a very simple one is 
java -Xmx4G -Xms4G -jar forge-1.10.2-12.18.3.2281-universal.jar -nogui
pause


if you have problems like i did that the server is laggy and unresponsive? then it has something to do with java garbage collection. then you might try a more complex script like i need to use. dont ask me to explain all of the switches but they work..



[start.zip](https://github.com/Darkosto/InvasionIssues/files/1047906/start.zip)

just unpack into your server folder and run the bat file
