### ISSUE TITLE
Too Many Open Files error crashes SinglePlayer game.

### ISSUE THREAD

**Issue by frenchiveruti** [Darkosto/InvasionIssues#321]
Also something along the lines of "Unable to write forced chunk data to " and also
" Something went wrong trying to save WorldData for world "
Here's the log:
https://paste.ee/p/aF4k1

**Comment by Mattabase** [comment]
Hey, do you mind reposting this log please?

**Comment by frenchiveruti** [comment]
@Mattabase Hi there, my HDD died with all that. so nope, sorry!
