### ISSUE TITLE
Minecolonies and torches

### ISSUE THREAD

**Issue by FFzoz** [Darkosto/InvasionIssues#324]
I don't know if it's a bug or if it's for make the game more difficult.

Minecolonies have schematics for buildings with a lot of torches. But with another mod, torches burns wood and wool like lava or fire so my citizens can't build anything.

Otherwise nice modpack. I really enjoy it.

**Comment by DemitriusM** [comment]
Can't say i've encountered this, the torches the colonists placed had no effect on blocks

**Comment by FFzoz** [comment]
Thx for your answer, you're right. I forgot I put torches before I started this quests. I break all torches and restarted the process and the houses don't burn now.
My bad
