### ISSUE TITLE
Player's arms flail in the air, unable to move.

### ISSUE THREAD

**Issue by Enderar** [Darkosto/InvasionIssues#325]
<img width="267" alt="screen shot 2017-06-14 at 10 13 38 pm" src="https://user-images.githubusercontent.com/29445166/27162341-bf23e306-514e-11e7-9364-b1c1caa1e022.png">
Touching any block makes the POV go crazy and spin out through blocks, making it unable to see anything.
<img width="623" alt="screen shot 2017-06-14 at 10 25 30 pm" src="https://user-images.githubusercontent.com/29445166/27190284-f35b472c-51c1-11e7-8d60-afe71ee2d432.png">
<img width="254" alt="screen shot 2017-06-14 at 10 25 34 pm" src="https://user-images.githubusercontent.com/29445166/27190283-f3562a62-51c1-11e7-8c81-f8f2588a1ff2.png">
<img width="426" alt="screen shot 2017-06-14 at 10 25 45 pm" src="https://user-images.githubusercontent.com/29445166/27190282-f3540d90-51c1-11e7-8a29-c5799a74a524.png">

**Comment by Enderar** [comment]
<img width="623" alt="screen shot 2017-06-14 at 10 25 30 pm" src="https://user-images.githubusercontent.com/29445166/27162680-97fa5b14-5150-11e7-88e5-69b14218169f.png">
<img width="254" alt="screen shot 2017-06-14 at 10 25 34 pm" src="https://user-images.githubusercontent.com/29445166/27162681-98065860-5150-11e7-9cb7-ad1e39b0561b.png">
<img width="426" alt="screen shot 2017-06-14 at 10 25 45 pm" src="https://user-images.githubusercontent.com/29445166/27162682-9808b0c4-5150-11e7-9345-984f226a35c7.png">

**Comment by Enderar** [comment]
Touching any block makes the POV go crazy and spin out through blocks, making it unable to see anything.

**Comment by Darkosto** [comment]
Disable BettterFPS
