### ISSUE TITLE
Turret Issues (Mod)

### ISSUE THREAD

**Issue by unseennote** [Darkosto/InvasionIssues#36]
1. Turret bases sometimes crash the player.

2. Their config menu opens the inventory when pressing "e".

**Comment by Darkosto** [comment]
*should* be fixed in 1.0.1

**Comment by jamzam90** [comment]
Heres a crash log for it. Looks like its the turret mod derping out during rendering.
https://pastebin.com/QLCAa8QZ

**Comment by Darkosto** [comment]
Let me know if this continues in the newest update I put out last night.

**Comment by Darkosto** [comment]
No response, I assume it's fixed?
