### ISSUE TITLE
Stop Herobrine From Spawning on days 0 - 3

### ISSUE THREAD

**Issue by Darkosto** [Darkosto/InvasionIssues#4]
It's too difficult as the player is still getting geared up.

**Comment by GenDeathrow** [comment]
ok.. this should be fixed in version 1.2.14_b56. And herobrine is only allowed one spawn per day after day 3.. also I say day 3.. but to be honest, its day 2.. since 0 is a day. I may fix that later.

**Comment by GenDeathrow** [comment]
should already be fixed in your 1.0.1 version.
