### ISSUE TITLE
Minecolonies Fishing Hut Crashes & Others Not Working

### ISSUE THREAD

**Issue by RussianSanity** [Darkosto/InvasionIssues#40]
The forge and bakery from Minecolonies aren't even able to be built. You can place them down but when you right click them to request them to be built nothing happens. The construction tape doesn't even come up for them when placed down.

Also when you place down the fishing hut and right click it to see it's GUI it crashes the entire game (in SP, no idea about MP). There's that crash report: https://pastebin.com/SWpLR9rt

However I did notice that Minecolonies version in this pack is an older version, so their most recent updates for 1.10.2 may help with these issues. I'm not entirely sure though.

And the last thing I can think of is make sure Enderio is updated fully because Kleins and Opiniums no longer crash when placed down (according to changelog) in the newer versions.

If I find anything else I'll let you know. Hope this helps!

**Comment by RussianSanity** [comment]
Oh! Just thought of a few more!

When you die, you receive 2 HQM books in your inventory instead of 1.

Actually Additions Traveler's Sack is known for duping but that seems to be countered with having to right click everything on the ground so it works as it should. 

And keep an eye on an update for ExtraUtils2 for a fix for the QuantumQuarry silverfish bug. It's been known to crash servers hardcore due to the sheer amount of lag it causes trying to spawn silverfish in it's own dimension which isn't supposed to happen at all.

**Comment by Darkosto** [comment]
Heya, thank you for all the reports and information! I do ask that you create individual issues for each of these instead of inserting them all into 1 page. It makes it a bit harder for me to stay organized. 

I do appreciate you sending me your findings! :)

**Comment by RussianSanity** [comment]
Sorry about that! Was just thinking it was better this way instead of spamming you with issues lol. I'll do that now.
