### ISSUE TITLE
Drone hitboxes.

### ISSUE THREAD

**Issue by wzsanders** [Darkosto/InvasionIssues#41]
After initially being frustrated with the Wild Dog hitbox, I saw another issue that explained the use of the config to learn where to hit them. Now I am able to successfully hit the Wild Dogs 90% of the time. However, it is near impossible to hit the drones. Even with minecraft F3+B enabled and the hitbox showing, it never seems to register at all. I've died to them 8+ times solely because they would not take damage. Is this intended or is there some way to kill them that I am unaware of.

Thanks. Love the pack, but it is really frustrating to keep dying just because your hits aren't registering.

**Comment by jamzam90** [comment]
Use a crossbow/bow of some sort. Otherwise there is maybe a 10% chance of actually hitting them.

**Comment by Kashdeya** [comment]
All the hit boxes are 100% correct and will not be changed. The way DarkSoul combat works is you have to figure out when to hit and when to not hit. if you swing before your GREEN bar fills up you will miss 100% of the time. then on top of that you have 1.10 combat. So it is up to the player to figure out how to play the pack and get better at it.
