### ISSUE TITLE
 Please turn off the pyromaniac torch.

### ISSUE THREAD

**Issue by Sabrewulf** [Darkosto/InvasionIssues#42]
A player base can be easily built with anti-mob-spawn blocks like open turrets blocks.

It just makes interaction with minecolony and villagers very sad. We can't just take a torch and put again or build a patch between homes without burn a house.
We love you, please don't burn our houses.

**Comment by daggit** [comment]
just find " # Adds Pyromaniacs to the mix, they will seek out blocks to catch fire. small chance increases with each raid difficulty [default: true]
    B:"Pyromaniac Class Enabled"=true
    S:"Pyromaniac Drops" <
        minecraft:skull:1:1:0.03
        minecraft:redstone:0:3:0.15"

in the raiders config/settings file and change the true to false that may stop that for you

**Comment by GenDeathrow** [comment]
That doesn't turn of what he talking about @daggit that only turns off raiders. He is talking about the torches burning. You can use blocks like glow stone instead of torches. Fire is part of the pack and will stay in release version.
