### ISSUE TITLE
Broken quartz texture

### ISSUE THREAD

**Issue by Liloa** [Darkosto/InvasionIssues#43]
<img width="1440" alt="screen shot 2017-03-30 at 12 14 52 am" src="https://cloud.githubusercontent.com/assets/8813897/24499877/e6bf82dc-14de-11e7-810d-b2c1c9a81747.png">
So it works as quartz because it is, but the texture and data number(I wanna say metadata but I dont wanna be wrong) is different. It also will not stack with quartz that I already have.

**Comment by Darkosto** [comment]
Duplicate post. This has already been reported and fixed in the new update.

Thank you!
