### ISSUE TITLE
blaze powder/rods dupe

### ISSUE THREAD

**Issue by XxpouglouisxX** [Darkosto/InvasionIssues#44]
so there are 2 recepys blazerods
![2017-03-30_13 38 38](https://cloud.githubusercontent.com/assets/26741490/24502498/57c36146-154e-11e7-9215-c21f2a4edc09.png)

and whit the 2 blaze powder=1blaze rod you cna just put in in a pulvus and get 4 blaze powder out of 2 blaze powder
![2017-03-30_13 41 35](https://cloud.githubusercontent.com/assets/26741490/24502550/99865214-154e-11e7-8bc9-5dcbdfa6e408.png)

**Comment by Darkosto** [comment]
Fixed in 1.0.1, thank you!

**Comment by XxpouglouisxX** [comment]
np thats why you have people to find the little tings :P
