### ISSUE TITLE
HQM crashing client

### ISSUE THREAD

**Issue by CookieHunteRRR** [Darkosto/InvasionIssues#45]
It crashing after i added a person to the party (before i could enter this gui) but now it just crashing

https://gist.github.com/anonymous/200fd49af5079f0c0282d86d46e4dd0f

**Comment by CookieHunteRRR** [comment]
also it happens sometimes, not always

**Comment by Kashdeya** [comment]
This should be fixed in the newest version. Please test it out and let us know if you get a crash.

**Comment by Yorkforce** [comment]
It's probably related to the same thing thats happening in #25

**Comment by Alexei-B** [comment]
I had this problem (on 1.0.4) when I invited a player to my HQM party prior to that player finishing loading into the server. I didn't crash, but he couldn't see the invite (even if I uninvited and reinvited) and he crashed if he tried to create a party himself.

Deleting the world and restarting, then inviting him after he finished loading completly fixed the problem.
