### ISSUE TITLE
Quantum Quarries Silverfish Bug - Watch ExtraUtils2 for update to fix this

### ISSUE THREAD

**Issue by RussianSanity** [Darkosto/InvasionIssues#48]
QuantumQuarries from ExtraUtils2 has a silverfish bug. It's been known to crash servers hardcore due to the sheer amount of lag it causes trying to spawn silverfish in it's own dimension where it mines from, which isn't supposed to happen at all. This has already been reported to the mod author so hoping this will be fixed sometime soon.

**Comment by Darkosto** [comment]
Is this something you've experienced in Invasion, or a general concern of the crash/mod? I noticed the responses in the ExtraUtils issue tracker mentions two mods that are not in this pack causing the issue.

**Comment by RussianSanity** [comment]
The mod itself. We've experienced it on Beyond Beyond (v 1.1.0) and SkyFactory3 (v 3.0.8) with the version of ExtraUtils2 named: extrautils2-1.10.2-1.3.0 
https://github.com/rwtema/extrautilities/issues/1382 is the report we put in for it but the 2 suggestions given below as a fix aren't within those two packs. We've been waiting to see if there are any updates which specifically name this problem but so far nothing. Haven't updated to the most recent version like what is within this pack but I'll be testing it out and seeing if it happens in SP before we have a chance to start hosting this pack. I'll let you know.

**Comment by RussianSanity** [comment]
Just mainly wanted you to be aware that this issue may come up if it isn't already fixed - could be a mod conflict like you said with another mod(s)

**Comment by Darkosto** [comment]
Okay! Thank you for the information!
