### ISSUE TITLE
How long is this Repo going to last without getting trolled?

### ISSUE THREAD

**Issue by vadis365** [Darkosto/InvasionIssues#5]
1 Week?
2 Weeks?
4 Weeks?
8 Weeks?
Waste of Money!

**Comment by ghost** [comment]
Github repos are free...

**Comment by Darkosto** [comment]
BYE FELECIA!

**Comment by slidingmike** [comment]
I'm still experiencing this issue. Please advise. Kappa

**Comment by Darkosto** [comment]
This freakin' guy!

**Comment by Darkosto** [comment]
CLOSING FOR NOW!
