### ISSUE TITLE
lcrdrfs and drones server configs not being applied

### ISSUE THREAD

**Issue by Yorkforce** [Darkosto/InvasionIssues#50]
We are currently on day 141 with the following server config settings:

lcrdrfs.cfg
    I:"Delay Time in Days Before Jet Pack Spiders Spawn"=334
    I:"Delay Time in Days Before Laser Creepers Spawn"=342
    I:"Delay Time in Days Before T-R3X Riders Spawn"=350
and
drones.cfg
    I:"Delay Time in Days Before Saw Blades Break Blocks"=350
    I:"Delay Time in Days Before Drones Can Shoot Saw Blades"=320
    I:"Delay Time in Days Before Drones Spawn"=300

However the T-R3X, Laser Creepers and Drones are already spawning in the world, haven't seen the Jet Pack Spiders yet but they are likely spawning too.

**Comment by Darkosto** [comment]
Interesting, they seem to obey the days I've set for single player. I'll let the mod dev know.

**Comment by Yorkforce** [comment]
It might be related to:
https://github.com/GenDeathrow/PlayerRaiders/issues/2

Noticed the fork :slightly_smiling_face:

**Comment by Darkosto** [comment]
Hey @GenDeathrow

**Comment by GenDeathrow** [comment]
Nope this is different.. mine was actually working on server side, but client was reading the client config. So So if server was 100 days, but clients config was 5 days And it was currently day 100. Than when the player logged on. The client would think it was Raid difficulty 20. But the server knew it was only Raid difficulty 1. So mobs would be the right scale.

**Comment by GenDeathrow** [comment]
Question did you have the server up and running before you reset the time back to 0? And for how long do you think, cause I think I know what the issue may be.  @Yorkforce

**Comment by GenDeathrow** [comment]
@vadis365 you may need to switch your checks over to using "getWorldTime" instead of "getTotalWorldTime". Since sometimes servers will set up spawns in the begining So the world will technically be running before ppl  actually join. And even if they set the time back to 0 via commands. The getTotalTime will  show the full time the server's world has been running instead of the current minecraft day player's see.

**Comment by Yorkforce** [comment]
@GenDeathrow I think the server was at around Day 40ish originally when we did the /time set command which switched it back to day 0, we then did doDaylightCycle false for a few (RL) days to set up spawn and allow the server to gather a few more regular players before letting it start ticking up in terms of difficulty.

Are you thinking it's been ticking up all the time?

Just checked the level.dat file and it has the following values:
DayTime: 4101975 (which would make it day 170ish which seems to be correct, server is showing day 170)
Time: 9328008

**Comment by GenDeathrow** [comment]
Yeah that's exactly what I'm saying. I believe its calling for a timestamp that starts when the world is created and always runs and is not affected by world time changes(or daynightcycle false). so lets say you did that 3 RL days ,that's what around 260 MC days + the 40 you had before + 170 now. That's well over the numbers you set in the config.

**Comment by Yorkforce** [comment]
Would seem to confirm the changes I made in the level.dat file, i set both DayTime and Time to 1 and the laser creepers have stopped spawning, so aye looks like it's grabbing the Time entry and not the DayTime entry.

**Comment by vadis365** [comment]
Hello,
Yes. I can confirm the time stamp I'm using is based off server run time eg. from when the server is started. The mods were set up to work from when a new world is created and run off the server clock which would ignore any resetting in game of time changes. I can implement the changes @GenDeathrow has suggested no problem in the next round of mod updates. For now in order for things to work the way you need it to you will have to do the Maths manually until I can push out the changes that are required. Sorry for the inconvenience but the time feature was added to the mods based on single player hardcore testing and needs to be changed now.
Cheers,
Me.

**Comment by Yorkforce** [comment]
I do agree, this was technically an issue we created ourselves due to vigorous server setup (we are a bit OCD when we open new servers). But I do think it would be easier/better for other server owners if the time feature was switched over to DayTime just incase they do something similar.

Thanks for quick responses and input, it's been very helpful.

**Comment by GenDeathrow** [comment]
Fixed for update 1.0.3
