### ISSUE TITLE
Minecolonies + Torches = Fire

### ISSUE THREAD

**Issue by andr9528** [Darkosto/InvasionIssues#52]
When starting minecolonies, every building is made of wood, and to finish the building the builder has to place down torches, which with the config that lets torches set fire to stuff on, just means he will burn the building down

i have already turned off torch fire in my pack, which preventet my colony from burning to cinders, as i heavily really on minecolonies early and find it fun to work with.

**Comment by GenDeathrow** [comment]
The only torches that catch stuff on fire are the ones placed by players. Darkosto has already tested this and the ones placed by the them don't catch things on fire. its only when you place it.

**Comment by GenDeathrow** [comment]
https://github.com/Darkosto/InvasionIssues/issues/28  << here is the link
