### ISSUE TITLE
Ore Excavation + Gravity? = Deletion of blocks

### ISSUE THREAD

**Issue by andr9528** [Darkosto/InvasionIssues#53]
While chopping wood using Ore Excavation i found that i only got a handfull of what i actually chopped. I were chopping down 4-5 Oak trees and one of them where a big one, which should have given me around 40 wood, but after chopping down the trees and collecting everything on the ground i had only gotten 14 logs of wood

I have turned off the gravity on all blocks config setting in my pack, which did fix this issue.

**Comment by Darkosto** [comment]
Not something that can be fixed since I won't be removing either of the mods. Thank you for the report!
