### ISSUE TITLE
Trying to setup server on my own computer issue

### ISSUE THREAD

**Issue by ChenTheEngineer** [Darkosto/InvasionIssues#54]
I tried to setup a server on my own computer but something went wrong.
Here is the crash report.
https://pastebin.com/ZyKUBy4y
Is the Biometweaker that break the server,How do I fix that?
Thanks for the help!

**Comment by Kashdeya** [comment]
From the looks of it you are trying to use the client files to make a server. This is not the right way to do it. 

Go to
https://minecraft.curseforge.com/projects/invasion/files/2400639

Download the proper server files and make sure to read the readme file for all the info you need to make a server work.
