### ISSUE TITLE
File/Folder Capitalisations - Linux

### ISSUE THREAD

**Issue by Yorkforce** [Darkosto/InvasionIssues#56]
Just running through our version update to 1.0.2 now, we noticed the following files/folders were recreated in lowercase on the linux server:
config/adhooks (from AdHooks)
config/hardcorewither.cfg (from HardcoreWither.cfg)
script/loottabletweaker (from LootTableTweaker)

**Comment by Darkosto** [comment]
Fixed in 1.0.3

**Comment by Darkosto** [comment]
The file names or the folders are lowercase?

**Comment by Yorkforce** [comment]
Both the file (HardcoreWither.cfg) and folders (AdHooks and LootTableTweaker) were uppercase, linux recreated defaults for all of them in lowercase.
