### ISSUE TITLE
Laser Creepers Spawning in Sunlight / Lit Area

### ISSUE THREAD

**Issue by andr9528** [Darkosto/InvasionIssues#59]
i'm on day 57 right now, and the amount of raiders have dropped close to 0, and instead the area is infested with Laser Creepers, that 2-shot me. i'm living on a platform that is inaccessible for mobs that can't fly, which is completely lit up with torches, but still sometimes Laser Creepers show up, no other mob seems to ignore the light level.
I have also seen 2 laser creepers standing in one of the minecolony level 1 citizen huts,, which i know is completely lit up by the builder, and the door was closed so they couldn't have walked in there
One time i even saw a group of 5 standing on the edge of my platform in an area that was completely lit up. All of theses events i have described occurred during the daytime

**Comment by andr9528** [comment]
Another group of 4 laser creepers just showed up right before midday, on the edge of my platform, where the lowest light level from torches is 8

**Comment by andr9528** [comment]
And a group of 3 just spawned while the time was close to midnight in a area that had a minimum light level from torches of 10. they seem to ignore light level and the fact that they should not be spawing in groups of more then 1

**Comment by andr9528** [comment]
Tell me if you want pictures of the locations that they spawned at, i have already marked them with redstone torches, for future memory of the locations, incase you need any information about the area

**Comment by Kashdeya** [comment]
This will be fixed in the next update.

**Comment by Darkosto** [comment]
Fixed in 1.0.3 as far as I can tell in testing. Thank you!
