### ISSUE TITLE
Recipe conflict

### ISSUE THREAD

**Issue by Inruke** [Darkosto/InvasionIssues#62]
The crafting recipe for MineColonies Building Tool is overwriten by stone spear from Kaishi's Weapons Pack.

**Comment by Kashdeya** [comment]
Was this not fixed in the newest version?
 if not it will be in the next update.

**Comment by Darkosto** [comment]
It should have been fixed in 1.0.2, is this not the case?

**Comment by andr9528** [comment]
Building tool yes, Scan tool no, tho i don't see what the scan tool is used for...

**Comment by Darkosto** [comment]
Fixed in 1.0.3, thank you!
