### ISSUE TITLE
Clicking cobble crashes game + Can't craft cobble

### ISSUE THREAD

**Issue by DrBoxy** [Darkosto/InvasionIssues#64]
When ever i need to click on the cobble recipe in nei/jei (idk which is it) the game will crash

also i cant craft cobblestone the recipe doesn't work for some reason

i reinstalled the pack 3 times and nothing is working

**Comment by Kashdeya** [comment]
#58 This is a NEI issue and will be fixed. 

as for cobblestone you need to use 3gravel and 1 clayball.

**Comment by DrBoxy** [comment]
the 3 gravel and 1 clay doesn't work either

**Comment by Kashdeya** [comment]
did not mean gravel sorry, to many things going on, the recipes for cobblestone in this pack are the following,
3 Stone pieces and 1 clay ball = 4
crafted like so
sc
ss

**Comment by DrBoxy** [comment]
The recipe may be bugged http://prntscr.com/erb8cq

**Comment by Darkosto** [comment]
Fixed in 1.0.3
