### ISSUE TITLE
Airdrops empty?

### ISSUE THREAD

**Issue by MysterTwitch** [Darkosto/InvasionIssues#68]
I just started playing this a few days ago, right before the update to 1.0.2

Before the update I was able to call in airdrops from the beacons and collect some early game metals to progress without much issue. 
I started a new world with the recent update, and now the airdrops are all empty canisters. I called in maybe 6 different drops with nothing inside. 

Was this intended? Are they gated behind some quest now or is this a bug?
Thank you

**Comment by GenDeathrow** [comment]
The only reason that would happen is if your littlelooter -> loot.cfg was corrupted or empty, or it was changed. You could post the config up here?

**Comment by MysterTwitch** [comment]
I will try a fresh install then. 

the only file is loot.json

**Comment by Darkosto** [comment]
This happens every so often. Generally a restart will fix this.

**Comment by MysterTwitch** [comment]
redownloaded the pack to get config files, now everything is fine.

**Comment by GenDeathrow** [comment]
Oops.. its loot.json. well at least it was fixed.
