### ISSUE TITLE
Disparity in Recipie for fruit punch and regular juice

### ISSUE THREAD

**Issue by hudson-75** [Darkosto/InvasionIssues#70]
What I mean by this is that fruit punch only requires a fruit and a sugar with the juicer and not the glass bottle that regular juice requires and fruit punch provides a half more hunger stick thing and 1.5 more saturation things.

**Comment by Darkosto** [comment]
Yeah, I should actually fix this. Thanks for the heads up!

**Comment by Darkosto** [comment]
Got this changed up for 1.0.3, thank you!
