### ISSUE TITLE
Evil Sand Quest not counting up correctly

### ISSUE THREAD

**Issue by andr9528** [Darkosto/InvasionIssues#71]
Crafted 3 sets of the soulsand recipe with raiders, which yielded 12 soulsand, but the quest only says i crafted 6

**Comment by Mattyzz** [comment]
I had a similar problem with the electrical fences and hardened blocks.
1 craft yield = 16 walls = 2/8
Or is it intended that we craft that many sets?

**Comment by Kashdeya** [comment]
This is a shift click issue with HQM. It may or may not be fixed in the newest update. We will have to check on this.

**Comment by andr9528** [comment]
Even when you only craft one set at a time with shift click? the soul vial with the radier is unstackable after all.

**Comment by way2muchnoise** [comment]
It is a know issue which is kinda annoying to solve. See lorddusk/HQM#24

**Comment by Darkosto** [comment]
Should be fixed by lowering the amount needed for the quest. I know HQM is still looking into this, but I tried fixing on my end. Thank you!!
