### ISSUE TITLE
Wood planks + Clay Creosote bucket =/= Treated Wood

### ISSUE THREAD

**Issue by andr9528** [Darkosto/InvasionIssues#72]
The recipe for treated wood asks specifically for a bucket of creosote oil in the middle, but why not make it take any fluidcontainer that holds 1 bucket of creosote oil?

**Comment by Darkosto** [comment]
I'm not sure I understand your question. Creosote only appears in buckets, are you asking me to add a recipe for any and all tanks that can hold a bucket of creosote oil?

**Comment by andr9528** [comment]
The recipe for treated wood asks specifically for the iron bucket filled with creosote, i don't see why the player should not be able to use a clay creosote bucket instead of the iron one.

**Comment by Darkosto** [comment]
You mean this existing recipe? 

![image](https://cloud.githubusercontent.com/assets/10309699/24588207/2894ec6e-1792-11e7-91b2-4485f91b2455.png)


😛

**Comment by andr9528** [comment]
well you are correct the recipe exist, but JEI & NEI just doesn't show it, and doesn't allow the use of the "+" function to autofill the recipe.

**Comment by Darkosto** [comment]
Yep, I'm going to see if I can get this to show up in JEI.

**Comment by Darkosto** [comment]
Fixed in 1.0.3, thank you :D
