### ISSUE TITLE
AdvRocketry Holo-Projector Server crash

### ISSUE THREAD

**Issue by Yorkforce** [Darkosto/InvasionIssues#74]
Got another one for you :yum:

Advanced Rocketry Holo-Projector, when right clicking to show the projection the following server crash occurs:
https://pastebin.com/xy3m2tHs

**Comment by Darkosto** [comment]
Should be released by the Lib Vulpes dev to catch the error before a crash happens. I'll add it in when he releases it :)

**Comment by Yorkforce** [comment]
Fixed in 1.0.3, thanks! :)

**Comment by Darkosto** [comment]
You're welcome :D
