### ISSUE TITLE
NPC Heads recipe

### ISSUE THREAD

**Issue by Kaelthalon** [Darkosto/InvasionIssues#75]
I wasn't sure where to put this, so I am going to leave this here and hope someone can redirect me.

After killing a large number of randomly generated mobs, I have found to have a surplus of heads. Is there a way we can convert these heads into a universal "Steve" head for cleaner inventory?

**Comment by Darkosto** [comment]
There's not a Steve head in the game to convert into. I can probably make them convert into skeleton skulls instead.

**Comment by GenDeathrow** [comment]
Just like the Predator does.

**Comment by Darkosto** [comment]
Fixed in 1.0.3:

![image](https://cloud.githubusercontent.com/assets/10309699/24624737/c0a502da-187a-11e7-99ed-3e7997b972f4.png)
