### ISSUE TITLE
Pressing U on Tin Ingot Crashes Game

### ISSUE THREAD

**Issue by Badger-One** [Darkosto/InvasionIssues#77]
When I press the U button for NEI to look up the uses of a tin ingot from the mod "Base Metals" the game crashes. It happened multiple times after restarting game.

**Comment by Darkosto** [comment]
Yep! This one has been reported to the mod dev of NEI, just waiting on a fix from him. Thank you! :)

**Comment by djezek0929** [comment]
not just an issue with tin, but copper and a lot of other core metals for multiple mods as well.

**Comment by Darkosto** [comment]
Fixed in 1.0.3
