### ISSUE TITLE
Difficulty progression.

### ISSUE THREAD

**Issue by IamStig** [Darkosto/InvasionIssues#78]
I have a concern with the modpacks difficulty progression. I am fairly sure that you have linked progression to the player (increasing every 8 days so I understand) but the time appears to continue over different worlds.
eg I started a world without the ability to quest so I looked around for 6 (ingame) days and then for various reasons created 6 new maps playing for something like 4 days, 2 days, 3 days, 4 days, 0 days and 3 days.

On the 7th map I was bombarded constantly. So I uninstalled the modpack and reinstalled and this time I was able to play much more freely.

Oh and the main reason for restarting was that for 3 of the maps I spawned in water, the 3rd time so deep I could not get to the surface.

**Comment by GenDeathrow** [comment]
I can assure you it based on the current world, and does not carry over. The Difficutly progression is based on raiders which is the mod I maintain.  But we have noticed some world seeds are just harder. RNG is always a factor from some of this. I have seen worlds they have almost no mobs, and others that are over-run with mobs. Also all those days are still in Raid difficulty 0 (i.e. under day 8). Mobs do not get harder till day 8. 

As far as the water spawning, its one reason why we gave players the resistance for so long. Its an issue that was with vanilla, but BOP has much deeper water.
