### ISSUE TITLE
gravel redstone gilded hammer

### ISSUE THREAD

**Issue by Chromogen** [Darkosto/InvasionIssues#79]
hey darko,

i thought about it for a while and i think this is still okay unless you have to find the hammers.
make it a feature! one hammer lasts for 30-40 redstone. if you want to nerf, just decrease the durability. you could also mention it in the book xD

so long and thx for all the fish!
Chromogen

**Comment by Darkosto** [comment]
Actually, decreasing the durability is not a bad idea. I like that a lot! Thanks for the tip :D

**Comment by Chromogen** [comment]
i would recommend a modifier like 0.7
that should be enough to actually search for /use it
it still is annoying to get the gravel + smack it + not get raided in the meantime (!!)

(actually got killed by a raider named Darkosto while doing it today - wish i had a screenshot)

**Comment by Darkosto** [comment]
Fixed up in 1.0.3, thank you! :D
