### ISSUE TITLE
Holo-Projector not registering for Ticket to the Skies

### ISSUE THREAD

**Issue by Boomflex** [Darkosto/InvasionIssues#81]
Quest "Ticket to the Skies" in 7. Blast off does not register the Holo-Projector which is Quest Reward from "I'm a Lumberjack" in 4. Automation. It seems to require fresh crafted Holo-Projector. This seems wasteful.

NBT issue?

**Comment by Darkosto** [comment]
Should be fixed in 1.0.3, Thanks!!

**Comment by Yorkforce** [comment]
Confirmed, its fixed :)
