### ISSUE TITLE
Iron Helmet with One Probe can't be fixed in Anvil.

### ISSUE THREAD

**Issue by Boomflex** [Darkosto/InvasionIssues#82]
Iron Helmet with One Probe can't be fixed in anvil with iron.

This may be a DungeonTactics issue, so just close if it is and I will send to the Dev.

**Comment by Darkosto** [comment]
I just spoke with McJty and his response was "I didn't try, I'll check it out later"

**Comment by Darkosto** [comment]
Use Duct Tape for this, or the item repairer from AA to fix this item.
