### ISSUE TITLE
Cyberware lost on death [surgery]

### ISSUE THREAD

**Issue by BloodWorkXGaming** [Darkosto/InvasionIssues#88]
Even tho keeping the stuff on death is enabled, if you fail the surgery you will still lose the stuff.
And there is no way of getting them besides the quest.

**Comment by Darkosto** [comment]
That's actually not how the config is set. It's set that you do lose your upgrades on death. You're reading the incorrect line, the one that says you physically drop them when you die. This line has to do with losing upgrades on death:

    # Determines if players keep their Cyberware between lives. Does not change settings on existing worlds, use /gamerule for that. [default: true]
    B:"Default for gamerule cyberware_keepCyberware"=false

Anyways, this has been changed in the new version so it's not a problem anymore.

**Comment by BloodWorkXGaming** [comment]
Well, I am playing with the prerelease Version of the pack where that setting is changed.
It was an existing world, so we would have to change the gamerule tho.

On the other hand, enabling to keep the upgrades may cause serious fuckups when intalling stuff wrong...
Like no power or no eyes.

**Comment by Darkosto** [comment]
I'm a bit confused here, it sounds like either option is not suitable in your opinion. Is there something you are suggesting to make it work better for players?

**Comment by BloodWorkXGaming** [comment]
Not really, no.
For the first problem, that it is only for new world, is there a way to call a command on first world startup but not afterwards anymore? (if you know what i mean)

and how does the dropping of the stuff work, like drop it onto the ground or into a grave/how is it dealing with keep inv?

Maybe a warning in the questbook might be appropriate and note, that you first have to include batteries to your body.
