### ISSUE TITLE
Pelted Quest Issue

### ISSUE THREAD

**Issue by andr9528** [Darkosto/InvasionIssues#89]
Uhm... broken quest?

![2017-04-03_19 57 42](https://cloud.githubusercontent.com/assets/21788044/24623228/08a033ca-18a8-11e7-9726-da1cafb36732.png)
![2017-04-03_19 57 54](https://cloud.githubusercontent.com/assets/21788044/24623236/0c2a1402-18a8-11e7-815f-33b56dc45f34.png)

**Comment by Darkosto** [comment]
I just tested and it worked for me. Try logging out and back in?

**Comment by andr9528** [comment]
that quest have been sitting like that for some time but...
i Relogged as you said, after doing a bunch of quest in category 1 and 3, and now my quest book has reset its progress o.o

![2017-04-03_21 30 40](https://cloud.githubusercontent.com/assets/21788044/24627337/d1c6953a-18b4-11e7-9861-4c79667b2dd6.png)

**Comment by andr9528** [comment]
Reset my progress too where i were, luckily i remember things about games pretty well :D, did a backup, and now gonna relog to see if it resets again (plz no... i don't want any more YAAAAY's...)

**Comment by andr9528** [comment]
Quests did not reset and now the Pelted quest was able to be claimed, don't know how that came to be or why it reset. might be something you have to keep an eye open for in the future.

**Comment by Darkosto** [comment]
That's really strange o.0

Also, if that ever happens in the future, use the command "/hqm edit", this will allow you to shift-click to complete quests when bugs like that happen and you want to continue.

So strange though! I'll be keeping a close eye on this. Thanks for the information!

**Comment by andr9528** [comment]
I did use the hqm Edit :)

**Comment by Darkosto** [comment]
Cool! Just making since not everyone knows about it. Thank you again for the updates :)

**Comment by andr9528** [comment]
No need for this to stay open, as the quest have been turned in, keep an eye open for hqm resets tho
