### ISSUE TITLE
Fluid transfer node does not use up clay bucket

### ISSUE THREAD

**Issue by andr9528** [Darkosto/InvasionIssues#91]
if i'm not wrong the recipe normally eats up the bucket, but does not when using the clay bucket, haven't tested with a normal iron bucket as i'm not that far yet,

might be something that you, Darkosto, have turned on, as buckets is a bit harder to get, just want to be sure about it

![2017-04-03_21 08 50](https://cloud.githubusercontent.com/assets/21788044/24626656/43cbf1aa-18b2-11e7-9894-60b475e758d8.png)
![2017-04-03_21 08 55](https://cloud.githubusercontent.com/assets/21788044/24626664/4537edf0-18b2-11e7-8d5a-70438669c25c.png)

**Comment by Darkosto** [comment]
Yeah, I'm actually okay with this happening :) Thank you for the report though!
