### ISSUE TITLE
Flailing arms and legs around.

### ISSUE THREAD

**Issue by ghost** [Darkosto/InvasionIssues#92]
Logged on to my world an my guy is flailing his arms and legs around and moving so fast its like teleporting lol. Also when I teleport the game drops to around 3fps. 

![2017-04-03_17 25 51](https://cloud.githubusercontent.com/assets/26884137/24632494/2ca7db76-1879-11e7-82a6-ada9691ee75c.png)
![2017-04-03_17 25 46](https://cloud.githubusercontent.com/assets/26884137/24632495/2ca87b76-1879-11e7-82f3-d0c439441bd9.png)

**Comment by ghost** [comment]
And now I am arm and legless lmao. 
![2017-04-03_17 30 06](https://cloud.githubusercontent.com/assets/26884137/24632634/c2ef3d54-1879-11e7-8cf3-9e68d508354b.png)
![2017-04-03_17 30 02](https://cloud.githubusercontent.com/assets/26884137/24632635/c2ef4c86-1879-11e7-9425-7654983e1bb8.png)

**Comment by Darkosto** [comment]
Take out BetterFPS

**Comment by ghost** [comment]
Thanks buddy love the mod pack.

**Comment by Darkosto** [comment]
No worries, glad you're enjoying it :)
