### ISSUE TITLE
No blocks can be mined in survival or broken in creative

### ISSUE THREAD

**Issue by Inf3rn0666** [Darkosto/InvasionIssues#95]
After the last update no blocks on my multiplayer server are able to be broken. They disappear after they are mined but after disconnecting then reconnecting they are still there. the raiders are able to mine the blocks fine. 

Also tried in creative mode and that still had the same problem

**Comment by GenDeathrow** [comment]
I don't really have an answer for it. This is for everyone, have you attempted to add: 
"spawn-protection=0" to the server.properties file? That would disable spawn protection and its just for testing purposes. I'd Rather rule out something before dark wakes up. 

Now I'm sure @Darkosto will jump on here and go, and give you a real answer. Especially since he knows the in's and out's of whats changed. I do not.

**Comment by Inf3rn0666** [comment]
Yeah spawn protection is off. I went creative a flew quite a distance before trying to break more blocks and still had the problem

**Comment by GenDeathrow** [comment]
Wasn't put into adventure mode? any console spam?

Edit: I'll be heading to bed very late here.

**Comment by Inf3rn0666** [comment]
OKay so the debug console comes up with this...This is from the point I joined and destroyed two blocks.

`[mMr_Inf3rn0[m joined the game[m> [07:39:48] [Server thread/INFO] [journeymap]: Mr_Inf3rn0 joining dimension 0[m> [07:39:48] [Server thread/WARN] [minecolonies]: EntityCitizen '6c33d8b3-2321-4cae-9599-6e02e0e277e8' attempting to register with Colony #1 as Citizen #8, but already have a citizen ('6c33d8b3-2321-4cae-9599-6e02e0e277e8')[m> [07:39:48] [Server thread/WARN] [minecolonies]: EntityCitizen '7f9b2988-36b8-4a89-ae70-07c8c4bcd5a1' attempting to register with Colony #1 as Citizen #7, but already have a citizen ('7f9b2988-36b8-4a89-ae70-07c8c4bcd5a1')[m> [07:39:48] [Server thread/INFO] [EnderCore]: Sending server configs to client for com.enderio.core.common.config.ConfigHandler[m> [07:39:48] [Server thread/INFO] [Actually Additions]: Sending Player Data to player Mr_Inf3rn0 with UUID ae47eb16-ab9f-4d92-aa57-bc8128e7c8e8.[m> [07:39:48] [Server thread/INFO] [journeymap]: Sending log in packet.[m>
19:40:23  [Error] [FML]: Index: 9 Listeners:[m> [07:40:23] [Server thread/ERROR] [FML]: 0: HIGH[m> [07:40:23] [Server thread/ERROR] [FML]: 1: ASM: com.feed_the_beast.ftbu.handlers.FTBUPlayerEventHandler@7e5ac348 onBlockLeftClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$LeftClickBlock;)V[m> [07:40:23] [Server thread/ERROR] [FML]: 2: NORMAL[m> [07:40:23] [Server thread/ERROR] [FML]: 3: ASM: vazkii.quark.tweaks.feature.KnockOnDoors@1ce4ace5 leftClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$LeftClickBlock;)V[m> [07:40:23] [Server thread/ERROR] [FML]: 4: ASM: breakabletables.handlers.EventHandler@707ce208 onBlockInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$LeftClickBlock;)V[m> [07:40:23] [Server thread/ERROR] [FML]: 5: ASM: com.valkyrieofnight.environmentaltech.item.ItemMultiBlockAssembler@31b285a1 onPlayerInteractWith(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$LeftClickBlock;)V[m> [07:40:23] [Server thread/ERROR] [FML]: 6: ASM: class com.rwtema.extrautils2.backend.ILeftClickHandler$PacketSendLeftClick handleLeftBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$LeftClickBlock;)V[m> [07:40:23] [Server thread/ERROR] [FML]: 7: ASM: flaxbeard.cyberware.common.handler.EssentialsMissingHandler@ba446ee handleLeftClickBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$LeftClickBlock;)V[m> [07:40:23] [Server thread/ERROR] [FML]: 8: ASM: mrriegel.limelib.util.Eventhandler@5b01f1d1 left(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$LeftClickBlock;)V[m> [07:40:23] [Server thread/ERROR] [FML]: 9: ASM: class com.exidex.stg.LeftClickEventHandler onLeftClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$LeftClickBlock;)V[m> [07:40:23] [Server thread/ERROR] [FML]: 10: ASM: biomesoplenty.common.handler.AchievementEventHandler@163c8ae2 onItemUsed(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V[m> [07:40:23] [Server thread/ERROR] [FML]: 11: ASM: minetweaker.mc1102.ForgeEventHandler@f3b9f7c onPlayerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V[m> [07:40:23] [Server thread/ERROR] [FML]: 12: ASM: zmaster587.advancedRocketry.event.PlanetEventHandler@faf9b0 blockPlaceEvent(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V[m> [07:40:23] [Server thread/ERROR] [FML]: 13: ASM: com.sb205.missing_pieces.Utilities.PlayerEventHandler@d626b76 onPlayerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V[m> [07:40:23] [Server thread/ERROR] [FML]: 14: ASM: com.minecolonies.coremod.permissions.ColonyPermissionEventHandler@20cf4b8c on(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V[m> [07:40:23] [Server thread/ERROR] [FML]: 15: ASM: mob_grinding_utils.events.ChickenFuseEvent@321cb79a startChickenFuse(Lnet/minecraftforge/event/entity/living/LivingEvent;)V[m> [07:40:23] [Server thread/ERROR] [FML]: 16: ASM: com.kashdeya.knobcontrol.modulars.Events@2261fae2 witherSpawn(Lnet/minecraftforge/event/entity/EntityEvent;)V[m> [07:40:23] [Server thread/FATAL]: Error executing taskjava.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: net/minecraft/client/Minecraft at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_102] at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_102] at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?] at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?] at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?] at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?] at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?] at java.lang.Thread.run(Thread.java:745) [?:1.8.0_102]Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/Minecraft at com.exidex.stg.LeftClickEventHandler.onLeftClick(LeftClickEventHandler.java:32) ~[LeftClickEventHandler.class:?] at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_724_LeftClickEventHandler_onLeftClick_LeftClickBlock.invoke(.dynamic) ~[?:?] at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?] at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185) ~[EventBus.class:?] at net.minecraftforge.common.ForgeHooks.onLeftClickBlock(ForgeHooks.java:1019) ~[ForgeHooks.class:?] at net.minecraft.server.management.PlayerInteractionManager.func_180784_a(PlayerInteractionManager.java:145) ~[lv.class:?] at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:631) ~[me.class:?] at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:40) ~[ja.class:?] at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:10) ~[ja.class:?] at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fl$1.class:?] at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_102] at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_102] at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?] ... 5 more[m>
19:40:45  [Error] [FML]: Exception caught during firing event net.minecraftforge.event.entity.player.PlayerInteractEvent$LeftClickBlock@6b228171:java.lang.NoClassDefFoundError: net/minecraft/client/Minecraft at com.exidex.stg.LeftClickEventHandler.onLeftClick(LeftClickEventHandler.java:32) ~[LeftClickEventHandler.class:?] at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_724_LeftClickEventHandler_onLeftClick_LeftClickBlock.invoke(.dynamic) ~[?:?] at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?] at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185) [EventBus.class:?] at net.minecraftforge.common.ForgeHooks.onLeftClickBlock(ForgeHooks.java:1019) [ForgeHooks.class:?] at net.minecraft.server.management.PlayerInteractionManager.func_180784_a(PlayerInteractionManager.java:145) [lv.class:?] at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:631) [me.class:?] at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:40) [ja.class:?] at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:10) [ja.class:?] at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fl$1.class:?] at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_102] at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_102] at net.minecraft.util.Util.func_181617_a(SourceFile:45) [h.class:?] at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?] at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?] at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?] at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?] at java.lang.Thread.run(Thread.java:745) [?:1.8.0_102][m> [07:40:45] [Server thread/ERROR] [FML]: Index: 9 Listeners:[m> [07:40:45] [Server thread/ERROR] [FML]: 0: HIGH[m> [07:40:45] [Server thread/ERROR] [FML]: 1: ASM: com.feed_the_beast.ftbu.handlers.FTBUPlayerEventHandler@7e5ac348 onBlockLeftClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$LeftClickBlock;)V[m> [07:40:45] [Server thread/ERROR] [FML]: 2: NORMAL[m> [07:40:45] [Server thread/ERROR] [FML]: 3: ASM: vazkii.quark.tweaks.feature.KnockOnDoors@1ce4ace5 leftClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$LeftClickBlock;)V[m> [07:40:45] [Server thread/ERROR] [FML]: 4: ASM: breakabletables.handlers.EventHandler@707ce208 onBlockInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$LeftClickBlock;)V[m> [07:40:45] [Server thread/ERROR] [FML]: 5: ASM: com.valkyrieofnight.environmentaltech.item.ItemMultiBlockAssembler@31b285a1 onPlayerInteractWith(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$LeftClickBlock;)V[m> [07:40:45] [Server thread/ERROR] [FML]: 6: ASM: class com.rwtema.extrautils2.backend.ILeftClickHandler$PacketSendLeftClick handleLeftBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$LeftClickBlock;)V[m> [07:40:45] [Server thread/ERROR] [FML]: 7: ASM: flaxbeard.cyberware.common.handler.EssentialsMissingHandler@ba446ee handleLeftClickBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$LeftClickBlock;)V[m> [07:40:45] [Server thread/ERROR] [FML]: 8: ASM: mrriegel.limelib.util.Eventhandler@5b01f1d1 left(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$LeftClickBlock;)V[m> [07:40:45] [Server thread/ERROR] [FML]: 9: ASM: class com.exidex.stg.LeftClickEventHandler onLeftClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$LeftClickBlock;)V[m> [07:40:45] [Server thread/ERROR] [FML]: 10: ASM: biomesoplenty.common.handler.AchievementEventHandle
19:40:45  [Error] [FML]: Index: 9 Listeners:[m> [07:40:45] [Server thread/ERROR] [FML]: 0: HIGH[m> [07:40:45] [Server thread/ERROR] [FML]: 1: ASM: com.feed_the_beast.ftbu.handlers.FTBUPlayerEventHandler@7e5ac348 onBlockLeftClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$LeftClickBlock;)V[m> [07:40:45] [Server thread/ERROR] [FML]: 2: NORMAL[m> [07:40:45] [Server thread/ERROR] [FML]: 3: ASM: vazkii.quark.tweaks.feature.KnockOnDoors@1ce4ace5 leftClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$LeftClickBlock;)V[m> [07:40:45] [Server thread/ERROR] [FML]: 4: ASM: breakabletables.handlers.EventHandler@707ce208 onBlockInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$LeftClickBlock;)V[m> [07:40:45] [Server thread/ERROR] [FML]: 5: ASM: com.valkyrieofnight.environmentaltech.item.ItemMultiBlockAssembler@31b285a1 onPlayerInteractWith(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$LeftClickBlock;)V[m> [07:40:45] [Server thread/ERROR] [FML]: 6: ASM: class com.rwtema.extrautils2.backend.ILeftClickHandler$PacketSendLeftClick handleLeftBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$LeftClickBlock;)V[m> [07:40:45] [Server thread/ERROR] [FML]: 7: ASM: flaxbeard.cyberware.common.handler.EssentialsMissingHandler@ba446ee handleLeftClickBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$LeftClickBlock;)V[m> [07:40:45] [Server thread/ERROR] [FML]: 8: ASM: mrriegel.limelib.util.Eventhandler@5b01f1d1 left(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$LeftClickBlock;)V[m> [07:40:45] [Server thread/ERROR] [FML]: 9: ASM: class com.exidex.stg.LeftClickEventHandler onLeftClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$LeftClickBlock;)V[m> [07:40:45] [Server thread/ERROR] [FML]: 10: ASM: biomesoplenty.common.handler.AchievementEventHandler@163c8ae2 onItemUsed(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V[m> [07:40:45] [Server thread/ERROR] [FML]: 11: ASM: minetweaker.mc1102.ForgeEventHandler@f3b9f7c onPlayerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V[m> [07:40:45] [Server thread/ERROR] [FML]: 12: ASM: zmaster587.advancedRocketry.event.PlanetEventHandler@faf9b0 blockPlaceEvent(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V[m> [07:40:45] [Server thread/ERROR] [FML]: 13: ASM: com.sb205.missing_pieces.Utilities.PlayerEventHandler@d626b76 onPlayerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V[m> [07:40:45] [Server thread/ERROR] [FML]: 14: ASM: com.minecolonies.coremod.permissions.ColonyPermissionEventHandler@20cf4b8c on(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V[m> [07:40:45] [Server thread/ERROR] [FML]: 15: ASM: mob_grinding_utils.events.ChickenFuseEvent@321cb79a startChickenFuse(Lnet/minecraftforge/event/entity/living/LivingEvent;)V[m> [07:40:45] [Server thread/ERROR] [FML]: 16: ASM: com.kashdeya.knobcontrol.modulars.Events@2261fae2 witherSpawn(Lnet/minecraftforge/event/entity/EntityEvent;)V[m> [07:40:45] [Server thread/FATAL]: Error executing taskjava.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: net/minecraft/client/Minecraft at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_102] at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_102] at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?] at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?] at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?] at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?] at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?] at java.lang.Thread.run(Thread.java:745) [?:1.8.0_102]Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/Minecraft at com.exidex.stg.LeftClickEventHandler.onLeftClick(LeftClickEventHandler.java:32) ~[LeftClickEventHandler.class:?] at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_724_LeftClickEventHandler_onLeftClick_LeftClickBlock.invoke(.dynamic) ~[?:?] at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?] at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185) ~[EventBus.class:?] at net.minecraftforge.common.ForgeHooks.onLeftClickBlock(ForgeHooks.java:1019) ~[ForgeHooks.class:?] at net.minecraft.server.management.PlayerInteractionManager.func_180784_a(PlayerInteractionManager.java:145) ~[lv.class:?] at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:631) ~[me.class:?] at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:40) ~[ja.class:?] at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:10) ~[ja.class:?] at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fl$1.class:?] at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_102] at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_102] at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?] ... 5 more[m> `

**Comment by Ommina** [comment]
Based on the console spam (posted above), I've removed

stg-1.0.1.jar (Swing Through Grass)

from the server, and blocks are breakable again.  I did _not_ remove it from the client, and was still able to join the server, so it appears clients won't have to jump through any extra hoops to connect.

Great idea for inclusion, and killing things without hitting grass is certainly appreciated!  Just the same, we've decided that, for the moment, breaking blocks is slightly more important.

**Comment by Inf3rn0666** [comment]
yup that fixed it for me

**Comment by Exidex** [comment]
Sorry guys, looks like I've fucked up. Looking into it.

**Comment by Darkosto** [comment]
Hey @Exidex , not trying to put any pressure or rush you, but do you have an estimate to when you'll be able to check this out? Also, do you need some help from any of us? :) We're available to lend a hand if needed.

**Comment by Exidex** [comment]
I understand the pressure. So I used the Minecraft class that is not present on the server. I use it to get BlockReachDistance and to hit an entity. Now I need to find the substitution for it.

**Comment by Darkosto** [comment]
Is your repo public?

**Comment by Exidex** [comment]
No

**Comment by Darkosto** [comment]
Here's a couple of examples to help :) 

http://jabelarminecraft.blogspot.co.uk/p/minecraft-modding-extending-reach-of.html

https://github.com/Shinoow/AbyssalCraft/blob/1.10.2/src/main/java/com/shinoow/abyssalcraft/client/handlers/AbyssalCraftClientEventHooks.java#L95-L171

Hope this helps :D

**Comment by GenDeathrow** [comment]
@Exidex without looking at the code. Im sure your raytracing to find the entities. but as far as the blocks. are you using the "mc.playerController.clickBlock(blockpos, mc.objectMouseOver.sideHit);" as that send information from the client to the server to click on blocks?  This is as long as you dont change the block reach distance. Thats gets more confusing.

Edit: Im flying blind since I cant see the code at all. I could be way off on what your doing?

**Comment by Exidex** [comment]
@Darkosto I believe I figured it out. I want to somehow send it to you first to test it.

**Comment by Exidex** [comment]
@GenDeathrow can you test it? https://we.tl/IRah2SF3Ln

**Comment by Darkosto** [comment]
I'll test it out, too. It will take a few minutes :)

**Comment by GenDeathrow** [comment]
sorry working for next 6 hours+.. I wont have time today.

**Comment by Darkosto** [comment]
So far it looks like it's fixed up. I was able to hit mobs through grass and also break blocks.

**Comment by Exidex** [comment]
Sorry once again. I will upload it to the curse.

**Comment by Darkosto** [comment]
Don't be sorry, accidents happen. I'm glad we caught it early on.

**Comment by Darkosto** [comment]
Just got confirmation from another tester that it works in multiplayer @Exidex 

Thank you again! Once the mod is up on Curse I'll push a pack update :D
