### ISSUE TITLE
Issue Breaking Blocks in Server of 1.0.3

### ISSUE THREAD

**Issue by fearlessdragon0** [Darkosto/InvasionIssues#96]
I just Downloaded the server files and when I tried to break any blocks it rubber-bands back.  I can move perfectly normal and when in creative i can destroy blocks. I don't know whats causing this.

**Comment by GenDeathrow** [comment]
https://github.com/Darkosto/InvasionIssues/issues/95

**Comment by Darkosto** [comment]
Fixed in 1.0.4
