### ISSUE TITLE
Blocks do not break on server

### ISSUE THREAD

**Issue by Shadow77388** [Darkosto/InvasionIssues#97]
i downloaded the server files from forge and set it up but as soon as i went into fame i couldn't break any blocks even after i left the spawn protection. i did also make my own server files from single player with my single player configs and still couldn't break blocks on server but on single player i am able to break them with no problem. VERSION 1.0.3

**Comment by GenDeathrow** [comment]
https://github.com/Darkosto/InvasionIssues/issues/95

**Comment by Darkosto** [comment]
Fixed in 1.0.4
