### ISSUE TITLE
Gamecrash

### ISSUE THREAD

**Issue by Chromogen** [Darkosto/InvasionIssues#98]
WTF gameplay tweaks got a crafting table, the one with the book on top. if placed down and rightclicked it will crash the game. cant confirm if invasion or modbased bug, but still did not want to leave unmentioned.

also: 9x crafting table == unbreaking crafting table without ending your life with breaking sounds
-> did you add this on purpose?

**Comment by Darkosto** [comment]
The WTF should have been removed a while back, it must have sneaked its way back in, I'll look into that.

9x crafting tables = vanilla, yeah. And as soon as you place/open the GUI it becomes a breakable table. That recipe change was given for mods requiring a vanilla table and don't have options to change to another block.
